---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-config
  namespace: data-platform
  labels:
    app.kubernetes.io/name: dagster
data:
  TZ: "Australia/Perth"

  # Init DB
  INIT_POSTGRES_HOST: "${NATIVE_PG_HOST}"
  INIT_POSTGRES_SUPER_USER: "${NATIVE_USERNAME}"
