apiVersion: v1
kind: Secret
metadata:
    name: dagster-secrets
    namespace: data-platform
stringData:
    postgresql-password: ENC[AES256_GCM,data:XZSI+Uqekbfgajc7FjdTRgTYgb0K2g==,iv:2RbPt1qUmMrzam+Es3HrqPJnf2hDrLxjWrStyatefhQ=,tag:r5euk33iG04sqiA1L0Anpw==,type:str]
    #ENC[AES256_GCM,data:yDe6Qvt0ixk=,iv:6k4nHb2Kpgi6PJ1rrhrVWyL2kjPAuq0qGDb0Flco+EU=,tag:m/x4uDPqU7QPDRjShcpVTQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:651btnQ02A==,iv:SXan8ZM1cENd3cen2skdtl4tHIzWKxpcb8ZZSqDP3T0=,tag:cR5bJEghUYP6Sck3SMzt3g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kS1UCwX7RSphbyJlKw==,iv:bg4XpN67C9pjrRJMucCHyxi26hYqQUuH9c0aSrIfm/U=,tag:QWmtm7TE7zKQkrOfaRx/PA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1aA0w0Vg3ghg6sF7Fz4wAl9ftJq8iw==,iv:rM6v8tJPAPzwKRjSoX6zTwlavZmMc1JDTePFG6PXeE0=,tag:VJgtuojbtCk1Y1aHTmb/uQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:uUxnaUbOXLckWFJdloYW/KMl0iNuBQ==,iv:xA/KZEjt3ljvdRnCIjFGPfl2ClA4dXltGn3aZEowgKs=,tag:THq/3TVI9rmZ3DuIUsTHmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2pWQW5XVHJlMkRvUm1K
            ZzRVNFJFeTg4VE5WaVpHKzB4ZnpyVmhOL2tjClBFRDBJeGVwd1VXejFHTDhTbkVT
            WmRDdldsbm9FY1RpRytFWDFPZkVUU1UKLS0tIERyMkNRUEtxN0JSS1Y0T3grTHpx
            R21kcElkdXFZNDFZbEZCVHJ0eWdxd1UKdmgn0EDysEgl0Dn35JC9d6133R9ByzCm
            oMBqLV2pINDQ9xixqTRBjqxxPYDTdwxfFsWEvow63kZAQ4Tm+e3wGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-13T23:30:28Z"
    mac: ENC[AES256_GCM,data:KaGIRLcRhnjNRoH0bX6HmvHqc555usajJ0S5IGjXIY7NZK23H+yFXO+neremH16mMMOR2brXH06Rueu6mlouF2nf2RKItTBcPzW75ioXdD5VXtjYWcWUHZ03yIrFcSoBf5GQgBbU7Ifei+hpQCagXO9JyKZBIY9+27HESZ2FH68=,iv:FZooCOm/p7k3Ks9DyB2hTlyXLxfwMZIea2Iy1pKmRag=,tag:NE2FtEGMfR6I/qt3byf80w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
