---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app redis
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: *app
      version: 18.8.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  values:
    architecture: standalone

    auth:
      enabled: false
      sentinel: false

    master:
      podSecurityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      containerSecurityContext:
        runAsGroup: 1001
      persistence:
        existingClaim: local-volume-redis
      service:
        type: LoadBalancer
        loadBalancerIP: 10.172.90.31
