---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-wallabag
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-postgresql
    - name: cluster-apps-redis
  path: ./kubernetes/apps/self-hosted/wallabag/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
