---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-joplin
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-postgresql
  path: ./kubernetes/apps/self-hosted/joplin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
