---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostfolio-config
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: ghostfolio
data:
  TZ: "Australia/Perth"

  # Init DB
  INIT_POSTGRES_HOST: "${NATIVE_PG_HOST}"
  INIT_POSTGRES_SUPER_USER: "${NATIVE_USERNAME}"

  # App
  NODE_ENV: production
  REDIS_HOST: "${REDIS_HOST}"
