---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            dependsOn:
              - postgresql
              - redis
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.125.0
            envFrom:
              - secretRef:
                  name: &secrets ghostfolio-secrets
              - configMapRef:
                  name: &config ghostfolio-config
          
          postgresql:
            name: postgresql
            image:
              repository: docker.io/library/postgres
              tag: 16.1
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
            securityContext:
              runAsUser: 999
              allowPrivilegeEscalation: false
          
          redis:
            name: redis
            image:
              repository: docker.io/library/redis
              tag: 7

    service:
      main:
        ports:
          http:
            port: 3333

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Finance Dashboard
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: ghostfolio.png
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/widget.type: ghostfolio
          gethomepage.dev/widget.url: "https://ghostfolio.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GHOSTFOLIO}}"
        hosts:
          - host: &host "ghostfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
              
    persistence:
      local:
        existingClaim: local-volume-self-hosted
        advancedMounts:
          main:
            postgresql:
              - path: /var/lib/postgresql/data
                subPath: ghostfolio/pgdata
      nas:
        existingClaim: nas-volume-self-hosted
        globalMounts:
          - path: /nas
            subPath: *app
