---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets ghostfolio-secrets
              - configMapRef:
                  name: &config ghostfolio-config

        containers:
          main:
            image:
              repository: ghostfolio/ghostfolio
              tag: 2.54.0
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config

    service:
      main:
        ports:
          http:
            port: 3333

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Finance Dashboard
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: ghostfolio.png
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/widget.type: ghostfolio
          gethomepage.dev/widget.url: "https://ghostfolio.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GHOSTFOLIO}}"
        hosts:
          - host: &host "ghostfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
