---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghostfolio/ghostfolio
      tag: latest
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 3333
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Finance Dashboard
          gethomepage.dev/group: homesys widgets
          gethomepage.dev/icon: ghostfolio.png
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/widget.type: ghostfolio
          gethomepage.dev/widget.url: "https://ghostfolio.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GHOSTFOLIO}}"
        hosts:
          - host: &host "ghostfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    envFrom:
      - secretRef:
          name: ghostfolio-secrets
      - configMapRef:
          name: ghostfolio-config
