apiVersion: v1
kind: Secret
metadata:
    name: ocr4all-secrets
    namespace: data-platform
stringData:
    PLACEHOLDER: ENC[AES256_GCM,data:fB5TMg==,iv:R5ysU6wWVdocwpUQZwY7QIWBSK38zJv5qz2BeVb2h6c=,tag:jlfcvpFuT+374X9AEP3Rvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGNXUjI3UnFWYmhyMlpH
            VjBNU09NR1hxczRjZFVYWFdjUmJYWEd5TkZvCkYvNzF1ajd5YldyYS9ndFRoMmJZ
            MStabWRWOC92MDZUWDczV1pYa2RyWmMKLS0tIEt2ZEh0a05oNjRjaW93T2pTWmVa
            UVJwbjBhMnlUak1MTUlkTkhRS096UHcKlf4aMWplGATuvcDkpdewvSYLPOOcZoO0
            hV0LU3CjUZeLetevY7q74hkVp8WaaG3FGOrt6hSgHFNgCQ6Rdm9hAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T02:47:59Z"
    mac: ENC[AES256_GCM,data:iqUQHjEFwD6Ul4sq2VcRaeflUfkoSKIkCS9zJi+UzWysFYPlT5NPhussAkSB5K9hjhdTBGvzJpmoJjTSlK5cDihA45kAzzggTK4g2Q2RGwIVJWvGDtmQMYMSgOQGKfWDwunvAuAPZr8sJ/MyjHyRDKPQAP3oleZ0M/PRJOAA4K4=,iv:LXhbhO/PvhkMyIKsxbRsicylDqNOqZl2s7cqCU+x5rk=,tag:5afFWakrVVbsP/BNcgZcWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
