---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: &ns storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2024-01-01T16-36-33Z
            args:
              - server
              - /data
              - --console-address
              - :9001
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: &secrets minio-secrets
              - configMapRef:
                  name: &config minio-config

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.172.90.44
        ports:
          http:
            port: 9001
          s3:
            port: 9000

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Object Storage
          gethomepage.dev/group: data-platform
          gethomepage.dev/icon: minio.png
          gethomepage.dev/name: Minio
        hosts:
          - host: &host "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: &apihost "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: s3
        tls:
          - hosts:
              - *apihost

    persistence:
      data:
        existingClaim: local-volume
        globalMounts:
          - path: /data
            subPath: *app
