ansible_become_pass: ENC[AES256_GCM,data:pWgh1TvUabFq,iv:4HKMikZefOsT5nNfKLncSyS5QDPYzp+lrQ5jPvdIdB4=,tag:ozcnrwqmPA3uL7Bg92IL2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMXNqd3N2NUVZQkpWM3Iy
            MHVmczZtdHZpNWt5YTBGSXc2Q0RscFFvSEdVCnZUVFptZFNWWlN0czAxNDhIOEF1
            T1J2M0hZUjJpQ0FFNzVLZ29Eck94S0kKLS0tIFg5bUhHZ244dlMycFFOL3FGN25v
            RC9sazZjRVd2MkxlSmZuZ0hSMzI5dE0KjTRFhlKprjGP7r5y1feon/FPEaPmXPlb
            ysuwZMJ88MEIY/mP5SUU5vHvLxGeE7ZvnKVfKU2/WJJgHKH3V/elkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T06:52:14Z"
    mac: ENC[AES256_GCM,data:v97vPp0by9MAEU/Zgv5b0u+idNlO9AgpsgNsnxJcBk68ofTdDyzir7YFyAFQ5MigNNWvLfbWgJtTNjtbHGrLwBhKu6M7smWBX5OKKPML2lJWpZ2uJ8VSUthllAaXgbXU+QI2+mjOHdckpq/+RMIMgU+hTymf6p7zPq0juOFqxwE=,iv:zOTGTHxzupOZUO+XKV5o3JkZMHdor3A2Hsp/lR7PtZ8=,tag:S/mKiAusGMVv9ZrUx6rr0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
