---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: &ns media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-server

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.120.1
            envFrom:
              - secretRef:
                  name: immich-secrets
              - configMapRef:
                  name: immich-config
            resources:
              requests:
                cpu: 15m
                memory: 250Mi

    service:
      main:
        ports:
          http:
            port: 3003

    persistence:
      cache:
        existingClaim: local-volume-media
        advancedMounts:
          main:
            main:
              - path: /cache
                subPath: immich/models
