---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: &ns media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets immich-secrets
              - configMapRef:
                  name: &config immich-config

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.112.1
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
            resources:
              requests:
                cpu: 5m
                memory: 250Mi
              limits:
                memory: 2000Mi
            probes:
              liveness:
                enabled: False
              readiness:
                enabled: False
              startup:
                enabled: False
            #     custom: true
            #     spec:
            #       tcpSocket:
            #         port: 2283
            #       timeoutSeconds: 1
            #       periodSeconds: 10
            #       successThreshold: 1
            #       failureThreshold: 3
            #   readiness:
            #     custom: true
            #     spec:
            #       tcpSocket:
            #         port: 2283
            #       timeoutSeconds: 1
            #       periodSeconds: 10
            #       successThreshold: 1
            #       failureThreshold: 3
            #   startup:
            #     custom: true
            #     spec:
            #       tcpSocket:
            #         port: 2283
            #       timeoutSeconds: 1
            #       periodSeconds: 10
            #       successThreshold: 1
            #       failureThreshold: 3

    service:
      main:
        ports:
          http:
            port: 2283
            targetPort: 3001

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Photos
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: immich.png
          gethomepage.dev/name: Immich
          gethomepage.dev/weight: "10"
          gethomepage.dev/widget.type: immich
          gethomepage.dev/widget.url: "https://immich.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_IMMICH}}"
        hosts:
          - host: &host "immich.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: immich-tls

    persistence:
      library:
        existingClaim: local-volume-media
        advancedMounts:
          main:
            main:
              - path: /usr/src/app/upload
                subPath: immich/upload
