---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mage
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-postgresql
  path: ./kubernetes/apps/data-platform/mage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
