---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-vector
spec:
  instances: 1
  imageName: ghcr.io/bo0tzz/cnpgvecto.rs:16.1-v0.2.0

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: local-storage

  superuserSecret:
    name: &secret cloudnative-secrets

  enableSuperuserAccess: true

  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/pgvector
      endpointURL: https://s3.${SECRET_DOMAIN}
      # Note: serverName version needs to be incremented or changed
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster pgvector-v2
      s3Credentials:
        accessKeyId:
          name: *secret
          key: minio_access_id
        secretAccessKey:
          name: *secret
          key: minio_access_key
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      # volumeSnapshots:
      #   storage:
      #     name: pg-snapshot
      #     kind: VolumeSnapshot
      #     apiGroup: snapshot.storage.k8s.io
      source: &previousCluster pgvector-v1
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
