apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: media
stringData:
    #ENC[AES256_GCM,data:Z6+vGbmrIjxC5Q==,iv:3WC20+Ir4xH9MhZhX2/ARZ4L5Cne+BzlOjp3ZyFyONo=,tag:M/g6B5FDM32CtW/ti/FOUQ==,type:comment]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:z0GO80g+JJ9mbWQWo7uk,iv:s9v7olfekzMKyKmhJE2fLJTZdM3ADDqbBkLP38jZ8Ok=,tag:91obDbN0IVIGnLa1pgNtfQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:SxQLY+nah3Fpk8z6PKbutec/EmToHw==,iv:RXEYyf72tDxa88ufmM7VBoq5GbiuWyVqt8KM6qUPYtE=,tag:OEC8zq+G+tr4ylEpnt/T5w==,type:str]
    PAPERLESS_IGNORE_DATES: ENC[AES256_GCM,data:3ZjuBEm45jWJYbGNyZSkEn/1qvKz,iv:ehU6uhG+h1prsxPaIRJtopB3+LhZaX7pAwHC9PVzQqU=,tag:dbS2vg71zZeKHzaJNE26hQ==,type:str]
    PAPERLESS_AUTO_LOGIN_USERNAME: ENC[AES256_GCM,data:3e3SQ8W58A==,iv:3AHveknjrXpFerDHhzFgMxaEuBg5ZGIC/0uXP83s/Vg=,tag:6FJkSXmLis2N9stZLcq4aA==,type:str]
    #ENC[AES256_GCM,data:rxzHiJ6dSB8=,iv:KT2P40qOanvSbkmsj6BiyyKTJPmqWqEYt75h7dY3YeA=,tag:TI9GecAJzcFKlSzSk4XN3Q==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:2VVu6QOvAnOL,iv:Z5xOulmepZuk9ALIxHsfBIKwIcbSEdT5gx1q1kdDDak=,tag:n030C1poA7N+LeCaB9BP6A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:JZDrb0GMyU2doJjlr4zG,iv:AZUeWgnLT7RcC5fhFM4NejPhIsQ0KJqjTDxp8u4x7ow=,tag:rPz1ZbMy1WubksC19aJyGA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zt765a2hQ2teg9fXx5/wwAsjYTsgUQ==,iv:yp+ecNj92/Baan1EoM3MvaLGbPN8pSe9Q5rI45XWS/g=,tag:V8zQUVxDP9+gx4al8d31lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWEFaQklSZU5tYnRmclhB
            WWtnR3hWSmpRS3BmR2pkd1lUcVR0R1E4VFZVCkZkbGtZZlJZUkdmdWozQWpwL0lJ
            Ums4Ui9MUEI1NFo5QlR2K0dsNFhpd0kKLS0tIEk0eXA0Y0I5bXVzRTFVQW1lV0xa
            bWIvcVlMem1SWjRoMXFOVmdmM2xBSXMKk+y349VDgQbHiKwdUSgqJeHy0iBK2Rvf
            v5eRwE22Cc+y/cIkpw4zYngLaV6rcYQWzYi6UE2ZndZkrR3WKCxs1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T23:27:42Z"
    mac: ENC[AES256_GCM,data:8PywJRjWILiYOc5q1bKnNcczs0fp5oNpBWGHYBCgWKUNFplpuenUcQgzgwnIhVD4CeL58RMelRMIg1mu34T9VR0SKEhTfyHDk43XmENxcIv5FcBNh1XXtmOHQz2PFP6UG+3xBRYOTsYu7uFYGsuHVI1av5ZguDw86lO/ckA4vuY=,iv:txl/vzdds7xRHVRxWC8RYYzvE+Q6H9RX3Lgj9RIwomc=,tag:umDDZ+cd0kDdohQgkW1HIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
