---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/benphelps/homepage
      tag: latest
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    envFrom:
      - secretRef:
          name: homepage-secrets
    persistence:
      icons:
        enabled: true
        existingClaim: local-volume-self-hosted
        mountPath: /app/public
        subPath: *app
      config:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            name: homepage-secrets
        subPath:
          - path: bookmarks.yaml
            mountPath: /app/config/bookmarks.yaml
          - path: docker.yaml
            mountPath: /app/config/docker.yaml
          - path: kubernetes.yaml
            mountPath: /app/config/kubernetes.yaml
          - path: services.yaml
            mountPath: /app/config/services.yaml
          - path: settings.yaml
            mountPath: /app/config/settings.yaml
          - path: widgets.yaml
            mountPath: /app/config/widgets.yaml
      host:
        enabled: true
        type: hostPath
        mountPath: /tera
        hostPath: /mnt/tera
        readOnly: true
      nfs:
        enabled: true
        type: hostPath
        mountPath: /nfs
        hostPath: /mnt/fileserver
        readOnly: true
    serviceAccount:
      create: true
