---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: &ns self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.8.8
            envFrom:
              - secretRef:
                  name: homepage-secrets

    serviceAccount:
      create: true

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      icons:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /app/public
            subPath: *app
      config:
        enabled: true
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
      host:
        readOnly: true
        type: hostPath
        hostPath: /mnt/tera
        globalMounts:
          - path: /tera
      nfs:
        readOnly: true
        type: hostPath
        hostPath: /mnt/fileserver
        globalMounts:
          - path: /nfs
