apiVersion: v1
kind: Secret
metadata:
    name: airflow-secrets
    namespace: data-platform
stringData:
    connection: ENC[AES256_GCM,data:eoIr0oYm+4m9MS439I79Ou3oWZbRRqoJowpVmlHNJiDu5mrIpKD0Evx3c6vsXyarkqzbaC2/28iOP7B5Cjai9l0xm921N7Gkmw==,iv:a/ah5Sqq/GgcvTv3/6clpFGh1vNpb84zAOcAtyRZqmM=,tag:7Cvy1vtgSiurxaTil3FUmg==,type:str]
    webserver-secret-key: ENC[AES256_GCM,data:7bA/pFNs9PqhBQY0Wif/FcTN1+qoOg==,iv:ktpHPE3qTuiwD0boiskrvOCHzkK9xs4ahS9NI/bHECY=,tag:2o6ifkysENh/VMxUAo7UKw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:PIjOYPGP5maijDFoyAW1kFtHhhU=,iv:uB7as5aGf+RbRRSKRsi/RcgeXVpyYlN/S7pyIer/n1o=,tag:hQAByOs9WmrmuznSZa1vcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGNXUjI3UnFWYmhyMlpH
            VjBNU09NR1hxczRjZFVYWFdjUmJYWEd5TkZvCkYvNzF1ajd5YldyYS9ndFRoMmJZ
            MStabWRWOC92MDZUWDczV1pYa2RyWmMKLS0tIEt2ZEh0a05oNjRjaW93T2pTWmVa
            UVJwbjBhMnlUak1MTUlkTkhRS096UHcKlf4aMWplGATuvcDkpdewvSYLPOOcZoO0
            hV0LU3CjUZeLetevY7q74hkVp8WaaG3FGOrt6hSgHFNgCQ6Rdm9hAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T02:41:35Z"
    mac: ENC[AES256_GCM,data:mZadulE2FVpJj8aOzmaXYoh9js4KVaTcuiANrDPV6ts7b2PbOpsh8HZ0skdmfzZ1GBg2EOd65hAcpMftHxyXNF1y6AafH+IPITAV8EMJpNWobudRIcuOxdnkm3mDQ/fWiE01ytj/k5qKhlCHgay8z4Q8WqrhjapzasSciJx83TU=,iv:9QyoHZC9H3YvcaSysMDDS+MXOM5MIHHoUufrvsJ6r3M=,tag:2CEJEnX5LFp7boatRkizaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
