---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app airflow
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: airflow
      version: 1.13.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system

  values:
    useStandardNaming: true

    securityContexts:
      pod:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    ingress:
      web:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Orchestrator
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: /icons/airflow.png
          gethomepage.dev/name: Airflow
        hosts:
          - name: &host "airflow.${SECRET_DOMAIN}"
            tls:
              enabled: true
              secretName: *host
        ingressClassName: internal

    airflowPodAnnotations:
      reloader.stakater.com/auto: "true"

    executor: "CeleryExecutor"

    volumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: airflow-data-platform

    volumeMounts:
      - name: airflow-data
        readOnly: true
        mountPath: "/data/tera"

    extraEnv: |
      - name: AIRFLOW__CORE__LOAD_EXAMPLES
        value: 'False'
      - name: AIRFLOW__CORE__HIDE_SENSITIVE_VAR_CONN_FIELDS
        value: 'False'
      - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
        value: Australia/Perth
      - name: AIRFLOW__WEBSERVER__BASE_URL
        value: 'https://airflow.${SECRET_DOMAIN}'
      - name: AIRFLOW__WEBSERVER__DEFAULT_WRAP
        value: 'True'
      - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
        value: 'True'

    extraEnvFrom: |
      - secretRef:
          name: airflow-secrets
      - configMapRef:
          name: airflow-user-config

    data:
      metadataSecretName: &secrets airflow-secrets
      brokerUrl: "redis://${REDIS_HOST}:6379"

    webserverSecretKeySecretName: *secrets

    kerberos:
      enabled: false

    workers:
      args:
        - "bash"
        - "-c"
        - |-
          exec \
          airflow celery worker --without-mingle --without-gossip
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      persistence:
        enabled: false

    scheduler:
      enabled: true

    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false

    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    webserver:
      enabled: true

    triggerer:
        enabled: true
        persistence:
          enabled: false

    dagProcessor:
      enabled: false

    flower:
      enabled: false

    statsd:
      enabled: true

    pgbouncer:
      enabled: true

    redis:
      enabled: false

    elasticsearch:
      enabled: false

    cleanup:
      enabled: false

    postgresql:
      enabled: false

    config:
      logging:
        colored_console_log: 'True'

    dags:
      persistence:
        enabled: false
        # existingClaim: local-volume-data-platform
        # subPath: airflow/dags
      gitSync:
        enabled: true
        repo: git@github.com:GwynHannay/airflow-pipelines.git
        branch: "main"
        ref: "main"
        subPath: ""
        sshKeySecret: repo-ssh-secret

    logs:
      persistence:
        enabled: true
        existingClaim: airflow-logging-data-platform
