apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:35Wo5ad45/m6pI9adIGpJEdOMEhYcatN,iv:R2rRwIALTdjk1njEM9AD+i+r4iehXoti06ueiyE2NsI=,tag:KwjopEBGlQUtjOUbxylvcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNFJCM1FjelkyaTNwVVRq
            WWJ3S3RrSGNqYVMzNEQxVVhBOWI3dDBERFNJCjlDMjdkeWFEZ2tVQU0xSXpGb2ww
            MnBUMVNPWVFxS1pJZWEvL2k4QWRUWDAKLS0tIGxLOEdRY2tvN21jTXlQV1hpVFpx
            MHRqVlpsMGIwbzl5QWEyNkQ5eFROOVkKMavAS9vaw5aPubb2AKmPUQRlUJPtBoqe
            bwV0xt1cTc2qkcEKFjC/UON2Ze3MWkcdDlRDM/Q2/UCBDiSa0IpzzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T05:25:42Z"
    mac: ENC[AES256_GCM,data:REuurTXzNwf5Q8oAD81NNICauCLo4HLWwwW3F5irAWQUgIpPru6L+utIyF1ETIsVdkJH/VNGTXGeEbS2HdvqwlSPBMIwEv/PU8SKApVAPRsIZfM09aYn26xweuudVPyVIzs2lirIv4NWNI6iqLjlC+NL7l69XOjBpGEyG//h3t8=,iv:sQI75jndcpbWgJ6aOEcX4b3pszqeLZbcTlMrJM87WbM=,tag:PJrb5jl41unzF5vWtUDsqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
