apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:q7IhM9FhMX4iv5swYnz5U57l24gZAfke,iv:2uLs/QAfoSEcBEcaVQZ2It3wxyxKTntXcP5y1xeYYvg=,tag:ZBL013f9Ea4mBXIha4PFIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbWk0Sk85NkthNzI0YzdJ
            NWpNSzRMa1l1MGttWGg5Y0pxN0U0TzIydkc0CkhtWWhtM0ZPbFppSk0yTzZyKy90
            RnZLcjlubjJCdVlBeWRVaGR5SnNVV1EKLS0tIFFyTDNPWkpzS2FKOWFEOGxHcUlz
            VVgxVW9OTHRFNDlNRDBkY3BCNFR4ZUEK/YSrM0RZhvLaOK/fIZNmgTpdk8JZRKpw
            Dxkw2bTjVl11v8Fdgrx4+1bVoTonUQL3zABcXBOXxVAnat8f+nYb9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T00:21:24Z"
    mac: ENC[AES256_GCM,data:Z6grKlHSw/7J83cAwhakvI5h5SIWkz+133pqE2A6VPz4w/yT04ezNCM625v6GqP7hacWMh6J1xDiAZoGrRYHGPHzLu/88v0XAw+3Hku4qu83MbTZwZowJWeaTTE9htBFvYZqP33nZZfG010Sb5YwclVdgj8hntXBJvFT9AaDLTA=,iv:wrggj3mNeSBnSQvYpdicD6boGIr2SWfzEI9eJl+prvk=,tag:wtiG6lG2ST1GKvROO87DJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
