apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Q39VuQZPri0G64Pi9ONi7S8creikZ4Eh,iv:7YXsUd0kdjDvkP4G8eoKTCWMCFucNZReZG6PvtSu/mQ=,tag:9pbnLnerqhBjuhHPEr4oNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTmNRM2tmcm5RZUtzUkd5
            UmRCVEM0eWxkTDkrOGJrS1hmS2lSTDhvc2pNCnJlOUdqMmRKV1RFR2pjVkJpMFlO
            d2wvcDdkMmVzVlZ2NUkzUDdvYU1ibDQKLS0tIGpsSTlaNUtINHdENnYweFF2Qnoz
            dXNZakFZNk5iV01YV2c4SG9QaDlJbmsKaQlMHWvGkT+4HE4AFlBG5pI6kr3AT4WW
            EVyqG81BA3aVUyGTmBOS1Av9i+5JL9e+9Vv8/oDEbJOVsbhWa71RlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T02:23:50Z"
    mac: ENC[AES256_GCM,data:cDulI5uc0XNgaVUwNpZjRGAPGEptlNEnNZ85tbHo1fegeYkITjASKOURiHVXirLwCLsmAzxAcxRt4uCaS/Qo4qelcU8byNeitUnGnq+l6UkohAQtrBnnC3UByVOhDPZ9KGzdXR0sqAdou0ttSHJRZOhYRUOvIpKk2MD3/PFWpEY=,iv:OtVqQv04inbXcX7HOgrUagTaE6p0hYRvG7m9YDxwlDg=,tag:9s84ftXb9DVkyvphRtLRvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
