apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:2kvBdKzj7PTHh35nNWRDdydBuadlkzmV,iv:1Qzzuef1kNf9sFciy4/UHHqZhZxF5y4MmpSSSk8uJqY=,tag:4GWewOp9dE5lenCIeGT/zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVHo2RllWSGc0VllJWmcx
            UmZtTWMyWE1kK2lDQnZ3dERkblhmeUE3SlNJCnJ0dFFoRG0raysrUzRTb0JSN1FX
            YXRUN2N3NGI4b2YxK2lNQ1hhaUNEWjgKLS0tIGhOcE5Ic3RreElHbCt5UGxJakZE
            d29ucTNqazhPVDVMS1ZKVXViN0lCV1kKWxUAhl+aL5t0NMFq4zrFS6QaOzv3WWpw
            XFCLTR2FkFCwpwgooJDuweOkYHNpQTknVSI7WAguHfnRb5xHIOmTEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T20:30:44Z"
    mac: ENC[AES256_GCM,data:Nxr2cqt0ZA+I/zQJ9ehpxLk7K4njHGuvZg8kvVNzQJ3mbtNudBIzfT5/WVb5LvDLWMMXbs0gdbxkrAshho0JR8tr6JdG8bcWRBPUfEx5aQgFv40Hdpi0+8aSLzg/ID/4P5bE4AXOSrT5haYgv/ePdX9wRR5S7fDmJRounz1N/5g=,iv:vpy0YX0dWjdgQCOzlZwfnRwCPqWPO8m26QSH3quYSjs=,tag:/OjEWqYtypqynr/0uaIXrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
