apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rT+BLusKphV33tv1iJqwRobEZPuX4zKV,iv:M7L7ukrZWUhcsUt/5nFOM4p7D35FPo5r+vbewxlUmCc=,tag:A6k5H7zhWy9LZ5XfKfGHvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ak9VUmVuNHJoUFRhSU5S
            MWUzN3U4SmQvSFJ2K1hWdUx0UWgxcno0aURRCjllWHY4WktNVllKa1Jlc3V4SGhL
            SmIwVGg3UVFobDJZamVMbmtpL1VpcUUKLS0tIGpFb3BBTGlwVFh0VE1IL25FYUIv
            M2h4aWVqOXA3WlVTMFVvVFNwUVJhencKNGC3AwXzmFZILNLqRC6QkAvHs/8Q2jPU
            4rRbQonYdTYi9I6NS1U+Ls5V7XqOmGj0zaPjJCGdwEJli7eYYQ+z0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T00:47:08Z"
    mac: ENC[AES256_GCM,data:Bke8LT1Zymy/XZXlGSSSeZOyvtNyOXMOveCjAzBffu7H9vojRAQy395jrnsZ2Rbb9Huwi0jS87uSE7JTcwY1LTNs0RC8atxAsFuhA6YF079MDWHLI4DGjVBFbIqIg9Mm/AHVEG8xNGgdVIQlQM4bYSCmQhTaDraP2uhNwnND0xU=,iv:9oHUQOJbBJwN0HFCqXVu8zE7BpkCXe9j0+1xXXAxDzw=,tag:9oai7Qkz586eKlefJ5NuKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
