---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: datawarehouse
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-8

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: local-storage

  superuserSecret:
    name: cloudnative-secrets

  enableSuperuserAccess: true
