---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app superset
  namespace: data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 0.10.9
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system

  values:
    image:
      repository: apache/superset
    # runAsUser: 1000
    envFromSecret: superset-secrets
    extraEnv:
      REDIS_HOST: "${REDIS_HOST}"
      DB_HOST: "${DW_POSTGRES_HOST}"

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Dashboard
        gethomepage.dev/group: homesys links
        gethomepage.dev/icon: /icons/superset.png
        gethomepage.dev/name: Superset
      hosts:
        - &host "superset.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: false
    redis:
      enabled: false

    bootstrapScript: |
      #!/bin/bash
      rm -rf /var/lib/apt/lists/* && \
      pip install \
        psycopg2-binary==2.9.1
      if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
