---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app superset
  namespace: data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 0.10.9
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system

  values:
    runAsUser: 1000
    envFromSecret: superset-secrets

    supersetNode:
      connections:
        redis_host: "${REDIS_HOST}"
        db_host: "${DW_POSTGRES_HOST}"
        db_user: "${DW_USER}"
        db_pass: "${DW_PASS}"
        db_name: "${DW_DBNAME}"

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Dashboard
        gethomepage.dev/group: homesys links
        gethomepage.dev/icon: superset.png
        gethomepage.dev/name: Superset
      hosts:
        - &host "superset.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: false
    redis:
      enabled: false
