---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app superset
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 0.10.15
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: flux-system

  values:
    image:
      repository: apache/superset
    runAsUser: 1000
    envFromSecret: superset-secrets
    configFromSecret: superset-new-config

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Dashboard
        gethomepage.dev/group: *ns
        gethomepage.dev/icon: /icons/superset.png
        gethomepage.dev/name: Superset
      hosts:
        - &host "superset.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: false

    supersetNode:
      deploymentLabels:
        app.kubernetes.io/name: superset
