---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-influxv1
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/influxv1/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 10m
