---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app homer
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: b4bz/homer
              tag: v24.12.1
            env:
              - name: TZ
                value: "${TIMEZONE}"
              - name: INIT_ASSETS
                value: 0

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.172.90.50
        ports:
          http:
            port: 80
            targetPort: 8080

    persistence:
      config:
        enabled: true
        type: secret
        name: homer-secret-config
        globalMounts:
          - subPath: config.yml
            path: /www/assets/config.yml
          - subPath: docs.yml
            path: /www/assets/docs.yml
          - subPath: links.yml
            path: /www/assets/links.yml
          - subPath: mediarr.yml
            path: /www/assets/mediarr.yml
          - subPath: money.yml
            path: /www/assets/money.yml
      assets:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /www/assets
            subPath: *app
