---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homer
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        containers:
          main:
            image:
              repository: b4bz/homer
              tag: v23.10.1
            env:
              - name: TZ
                value: "Australia/Perth"
              - name: INIT_ASSETS
                value: 0

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.172.90.50
        ports:
          http:
            port: 80
            targetPort: 8080

    persistence:
      assets:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /www/assets
            subPath: *app
