---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-monitoring
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-monitoring
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/fileserver
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume-monitoring
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/homesys
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-monitoring
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-volume-monitoring
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-volume-monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  volumeName: nfs-volume-monitoring
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: host-volume-monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: host-volume-monitoring
  storageClassName: local-storage
