---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kopia
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: kopia/kopia
              tag: 20231025.0.151109
            command: kopia
            args:
              - server
              - start
              - --insecure
              - --address
              - 0.0.0.0:80
              - --without-password
              - --log-level
              - debug
              - --disable-csrf-token-checks
            env:
              TZ: "${TIMEZONE}"
            envFrom:
              - secretRef:
                  name: kopia-secrets

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Backups
          gethomepage.dev/group: homesys widgets
          gethomepage.dev/icon: kopia.png
          gethomepage.dev/name: Kopia
          gethomepage.dev/widget.type: kopia
          gethomepage.dev/widget.url: "https://kopia.${SECRET_DOMAIN}"
        hosts:
          - host: &host "kopia.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        readOnly: true
        type: configMap
        name: *app
        globalMounts:
          - path: /app/config/repository.config
            subPath: repository.config
      snapshots:
        existingClaim: nfs-volume
      vols:
        readOnly: true
        existingClaim: local-volume
