---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./helmrelease.yaml
  - ./kopia-secrets.sops.yaml
configMapGenerator:
  - name: kopia
    files:
      - config/repository.config
generatorOptions:
  disableNameSuffixHash: true
