---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-redis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-restore
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hostpath
