apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-restore
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hostpath
