---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pvc.yaml
  # - ./csi-pvc.yaml
  # - ./snapshot.yaml
  - ./cloudnative-pg/ks.yaml
  - ./influxdb/ks.yaml
  # - ./pg-recovery/ks.yaml
  # - ./pgloader/ks.yaml
  # - ./redis/ks.yaml
