---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pvc.yaml
  - ./cloudnative-pg/ks.yaml
  - ./influxdb/ks.yaml
  - ./influxv1/ks.yaml
  # - ./pgloader/ks.yaml
  - ./redis/ks.yaml
