---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-database
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-database
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  storageClassName: local-storage