---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-database-volume
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage