apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pg-snapshot
  namespace: database
spec:
  volumeSnapshotClassName: snapshot-local
  source:
    persistentVolumeClaimName: cnpg-restore
