---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grocy
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "backend"

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: docker.io/grocy/backend
              tag: v4.0.3-2
            envFrom:
              - configMapRef:
                  name: grocy-config
          frontend:
            image:
              repository: docker.io/grocy/frontend
              tag: v4.0.3-2
            envFrom:
              - configMapRef:
                  name: grocy-config

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Fridge ERP
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: grocy.png
          gethomepage.dev/name: Grocy
        hosts:
          - host: &host "grocy.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /var/www/data
            subPath: *app
