---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homebox
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/hay-kot/homebox
              tag: v0.9.2
            envFrom:
              - configMapRef:
                  name: homebox-config

    service:
      main:
        ports:
          http:
            port: 7745

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: House Inventory
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: homebox.png
          gethomepage.dev/name: Homebox
        hosts:
          - host: &host "homebox.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /data
            subPath: *app
