---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homebox
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/hay-kot/homebox
      tag: latest
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 7745
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: House Inventory
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: homebox.png
          gethomepage.dev/name: Homebox
        hosts:
          - host: &host "homebox.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    envFrom:
      - configMapRef:
          name: homebox-config
    persistence:
      data:
        enabled: true
        existingClaim: local-volume-self-hosted
        mountPath: /data
        subPath: *app
