---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: immich
data:
  TZ: "Australia/Perth"
  NODE_ENV: "production"
  LOG_LEVEL: "verbose"
  DB_DATABASE_NAME: immich
  DB_PORT: '5432'
  IMMICH_WEB_URL: http://immich-web.self-hosted.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.self-hosted.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.self-hosted.svc.cluster.local:3003
  MACHINE_LEARNING_PORT: '3003'
  TYPESENSE_HOST: immich-typesense.self-hosted.svc.cluster.local
  TYPESENSE_DATA_DIR: /config