apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: self-hosted
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:EdZwCEwWn15A8ek6,iv:JDwbASJNcIFRIFC9vf4JRNtqg3XomctRFmue/ZzkZOE=,tag:FTdC13tU7Lv+lOJtSw4zqA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:1sCKO6y3jbKI3OBgyUDLFVHbEA0=,iv:/Vl8+VvyK3iJDsBvqJ2SSYYd49FrncJ8AUvWldE9GNA=,tag:bRshIh90lHENbcHqOQzxuw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Nx8YqXyKkP9bna2SavuJFN+fmmMAZVBVokjwCRKCcdWFVJJaKIVZRTScd6BG//Jpf/GU5uKMCgA=,iv:YS05LGDjRqdNHf6O/GbHOsr+OMKPS+IDQWvsN6FGaFk=,tag:NUv/mXwZIH5rt0sZAwY43Q==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:Y1XFm+CCGvh2kL+zYmKJjN0xQl7LEEi5lyoWEGbwFOujSmxSFEfhyg==,iv:x3NyPn75bNF18OHv5AHJ2pCapzf6lsuf5f/t9VgPl9c=,tag:eIYMWkWgofjvX0fT53JUeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGh3bGZQQThxSHVtRjNH
            OVlsZDhsblVBRHZaOGpnaXZlRzZScUNaNmtnCnFtbStrTW5oek9nUFBoUTNEYmlx
            dU1rb3NLWjU2OE9oSFJ0T05NU0ZaQVEKLS0tIG12K05UakFuVE5hdlQ0V2UrVlkx
            SUpEbWg2OW1ZZU9jMkEyWG5qUXVwTXMKH5a1FDQ75sRu1wC6DWZCKBo1fnRY0YGy
            RL55yPCbts0UnG/2HcsgFIHrXyVao9YlGZ0utCcOlibofFZqCFVU/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T05:39:06Z"
    mac: ENC[AES256_GCM,data:krmmmN6Hkz3HUJdDsXAlewO1QfX5N7mO7J12e6UTRbqdbnLYNVmmhC/si3qjzM/uT8dG1r/VIF4ol6ZJ//Trpa+kymIS9mBLVOqDPZCz7et4129RXOov4/4fCftt7zNT7OyoNgK54pZaGqmACGwrAlyZCtQz3lF9IaCpdCDui74=,iv:2CV1rYvwWMW6xSCpfZ4IgLvU3TuywFIrTCuGAWIKj4Q=,tag:hxUayz4UlC97or/pdkkEZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
