---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app postgresql
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 12.12.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          postgresPassword: ${POSTGRES_PASSWORD}
    audit:
      logTimezone: "Australia/Perth"
    primary:
      service:
        type: LoadBalancer
        loadBalancerIP: 10.172.90.30
      persistence:
        enabled: true
        existingClaim: local-volume-database
        subPath: *app
