apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:TmUDk70FLVJyIHvj/cBnwhOtYBPKAjucAeY3TW7neVF843WgMFJutQ==,iv:rbzUL4wJIvldoR4naUP57z5HuoLBfPgKJ7imWb+SnS4=,tag:A2Uf1salvjW9sNv4OwbfIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdnlHamNDV2J0Rkdnd1dT
            d244dldpcmZJTGw0elNLOTVwRDYwYWRCUmdRCnlvZVV6YVVMSVZZTDJ4bkJoMFZF
            MmlHbHZTZ3RJV0QzamJIWmpadkY5cUUKLS0tIFZWR0xYOWg4bGdCN0NVTksvR3BG
            bnhnWXNqZWlvNzc0UFozME9LZ2FGYVEKt0MEMqshbjZnWPVBIP0W3p/hlY2xYEs5
            BgzlXw0aP/tUtpMsIlOzXcsH114T6gsrTy3AOK31ej0OeR6icmbPnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T00:21:24Z"
    mac: ENC[AES256_GCM,data:D/Wsrdy0bt/vYfEOEo79kGbDz+vsNzO7mtSMQXQFyo1RNMLVoJPGAK/80b49HGMWWkn7d4TphcQrbVuSypjcQA7dBDaHjm2MpunkSQRpyPK7JtUG/Q8oYnFQJ+gRhNsZ6BZ0z88QuXYOwO/5Ln9NVA1iptaYdVz5DEEvl/1xWOc=,iv:nxE97T+y8jWLldtwjQSr83A5e1Da989tDgHQaLwlM9w=,tag:Z3k4hwok3fF30rXHrX+QTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
