apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:A/2mWegOwamHPzQ+lsT9Pump5kQSn+VphDYW5CBYFAqXXqNCY3G1fg==,iv:JL/RU1Wx6Nq9u+H2naOTA5xotFp+ohS+1v+38zXpubk=,tag:JwMTzFuPsvPSGekPINNyqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aWxUWmlIUGMxeVJaUVRj
            dWRJd2kxTlh0Q2o4S1Fld0dEWnUxZkFVWW04CnFQcHBjbXhMSkdWRUtxRzJnR213
            YmVSdEhsS092UGxEQUlEUE1VLzhNaTAKLS0tIGgxQWVWMnVEMWZhdXhpWko2ZjNi
            aXVJUjlzNjVNSW80T0ZTbU5la1FnV1EKXME+zZefQm0P/6TbO39Pno7MscehAWIb
            j/XgZDl+VZz566XqY18gYeWUhAizFyupfskWqbNlEGhA1dVk1rX4Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T00:47:08Z"
    mac: ENC[AES256_GCM,data:TmSagGA5MCpafix5tBvJZUSdaKT9x1tb8nKYwx0AM9DDitdCZDEqtb7wyiOnGwGCYttmSlznztplkTTbeZNL5pxUlqzDTUO+L6Ux3M9CjF9GRp2lKpXLdVacARKjwXWTUVJng4Zq/yld4TtN5ptwUzAh2eto69uw/5mp7PPX08s=,iv:Ei+syF2aaeMjRGFKEtaj5JR1FxKT/fJYi8bvViX1gIs=,tag:s8hGjnVy45kh7AcX6IwcbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
