apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:6wNjO73BFWMBEX7GrrkKSO1n9HUpLSRdGrGCbsMTC2pU8XKnQUbuag==,iv:LmJur2enJGZWrPqS1k2ZTMAlyJRoSf1arY0VJVy0OH4=,tag:povfL2dUGWpaAbdYogEtmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MTRTbDVVN2luMUtMWGRW
            SUVQS0p0TlprWWJVVnBRc3IyWDdnNCswYVUwCjlwZ2t3N3ozL0tZSCt1Y3VJaG81
            bHpKZVlDUjhhMXlpcjQrSUFYTTZjbmcKLS0tIE1TczRrUWhsL05pcnp6YkxtUXZO
            VzNZb3NjNWZQM1BmdGxVaWNsVUNoUTAKrwoxTJu6VumPntX13OIDwdnfrHzD87vy
            NmL2gJCPMFqZIcaTeVaTWrdZ26EAjzztL8dLt4u9cky8nsH7kYmPxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T05:25:42Z"
    mac: ENC[AES256_GCM,data:IzT0Q4iUGw3WysuvHkbcq7kMWd3o9lkv/ERJQjfPpKIccnYXVvaP3UqiUVmYljBj/YjUweYn8wSDCtM446bLYmNt0eGMmnks0qbxD6o5ZaDMKwJ7/qroBwrzazETlXFhdcTS2UJQuxX4s6ivPFrO+Tbc8f1KgOlJT1YqurpWA7E=,iv:0S2p2hOGI/W58nSKfmLY2nDDlbZQ1wXBGMThNaz4axA=,tag:xCkELuUW2OaQHe2foJi+mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
