apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Yjqe18aAQ+9HSnJU1g6FUT8AZ0KNd9bTMP/bBDmupIJHYbPpGyoSyw==,iv:14KfCvAZpoia+n+ZYcsRJkkR4O5m8MKEeKPV6qZF24g=,tag:b8SGTQdkcQB39tgg/N+StQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RzhtVk16MW8wdWVnYWxB
            SHlzOWJ5bXdDSHhjbkZGbWk3YTRsTWRxTWlRCm5LVFlSWnRTNjVTOWErWTl3MEhs
            U1NEdXBhZUJOVDZQQ2VKRE44UkJsRUEKLS0tIGxZQ0FnZWg4d0FyVUNPQnpvQkRF
            SFhLZ0RYZlBIemZxRkQyWmFaQ3Z6SzQKFyNQXlS2rwDs76C2L4XbEArGNX2yqKcP
            iRp94j0YBP0kJDgeqbf4r9VMSqgr1ocngbedJS9/34ikXnF5Jay0bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T02:23:51Z"
    mac: ENC[AES256_GCM,data:hVDLqIeCEQYRxVzmKCUcEJwqfcgaalZaIQNeTTicCN4cbTld0zHhmefGc8p0nbtt8W+rdP6BZZ+vyncwNJjfLbY3EhgJIUEZXokdcSq1bx28zu1UijZSC99hgpnQkTgo2UWpuyglgYIL+X1GOmkmOuaQnUwEbpnidzLz8meDUWE=,iv:r9W0sLvH1MTxB0J2V50oGcsBn6tkNu6J4faBNIha7AQ=,tag:a9Kd5jhe1de6dYWsDESwGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
