apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:WPE0RniyeirYidV5PUi6KaWFX190UnChXi6iDoAFXqPiTw+9Se9jKw==,iv:/zrmmUaeRYN1TRGAXiOrOdHmyl50FaRNv3YdiQIIBrs=,tag:eCIXOuMfu9WCj8DT08tZwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc3FRU2RIdTJkWUF4VjQx
            b1VBVlZvMDVaMVBCMWhQUTBOUmRnTTBaMVQ0CnYzd3FWcHBGZVh2RVh5V3NTRE9m
            UUJpTWI4bVlXSDlwa01kbExTOFhrV1UKLS0tIDczdjdJT29jUXZvZHBGRys1SWdR
            SWhUc1ZMQmRJYUxmN281TWFNWngyRHMKYLVKzgcKzfP8awCh5Q/JMb1M6ZgRrqNl
            SCQ95GwDM0jetsrPbaN4LZp9TiVkf0IOTJbayda4Pm9v/m6urth3bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T01:39:42Z"
    mac: ENC[AES256_GCM,data:/jk3/e3Qvtzy7aYTiFoIBgq3fGJKgbdVzcjPQV+ZUtkUkxcXZ/xtVl8X6jwSL2NbnBw7o18ajX4Un7SNcMBi5x3qyOiVpXGGCOoNDW0XhzAyB8YfLvO0UCsGd6fI+EFrDuqPjZcD6WzQXIfdZxSKrEW6mzhBENOiC6fo41SVH6c=,iv:DcZI0Xj62CyvIBpg+1mM9plhiJRAsr5r1mr9boIEbuc=,tag:nBkXgJzBEtVcG+7e7DbI5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
