apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:eEBE/VCYONwHaDFRzo32P3YSA9FHdWU6zSnfQJqREa/fcGSSqtpRDw==,iv:KeiQI1bEG8GvIVSL9t3G6eMTSMipUSI+JX/23ai50mA=,tag:ojBvHKEPRv6u71uTn5Lq1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcU9zcFo2YWErcnIveTVh
            bE1Td0hWeUVwM0g1cmdHQkp4dE11cUtEWmpFCjFDQU8yNWxJNC9IWUdmRHF0OHRs
            d0tsd0NvaE13d1hmMzE0VnUzWWFDRTQKLS0tIGxvbS94YzBzSVRmYURzcjZnVUZn
            Nkx0NnE3V05XbHpMbkl1Wk5HM2J3djAKjp07tKn9ozoiXSciNJ0y95FziJbdmSt9
            l/TC1gBF91w5XknIhuNSjYW5pziJ0KetrpExRqlfImDhOLoiH6wpjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T20:30:44Z"
    mac: ENC[AES256_GCM,data:3NThIiLAU3PNVb1zrxz+HYVJDLyhOwJrx8bja3BYryxWWqezp8D1vjbh43UaZZio5PRvQK1Cpi20EYqM3pAILTAyyfD8ICniQi5UsLDZbfXha5oJ8fEA71/8Kg4ZkQI3KhGKcaQXEHLxwwFxlkCUKknJxExzjvY6SMCBDzEgAVM=,iv:ikWIRIFb4zvmaljoVw7GkxIkJYInnLe4ZjixZiSQ5xE=,tag:KVP5WvuX2hqkOrsq/XwyZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
