---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: &ns media
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            enabled: False
            dependsOn:
              - postgresql
              - redis
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.131.3
            envFrom:
              - secretRef:
                  name: &secrets immich-secrets
              - configMapRef:
                  name: &config immich-config
            resources:
              requests:
                cpu: 5m
                memory: 250Mi
              limits:
                memory: 2500Mi
          
          postgresql:
            name: postgresql
            image:
              repository: docker.io/tensorchord/pgvecto-rs
              tag: pg16-v0.2.1
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
            # securityContext:
            #   runAsUser: 999
            #   allowPrivilegeEscalation: false
          
          redis:
            name: redis
            image:
              repository: docker.io/library/redis
              tag: 7
      ml:
        enabled: False
        dependsOn:
          - main
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          ml:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.131.3
            envFrom:
              - secretRef:
                  name: immich-secrets
              - configMapRef:
                  name: immich-config
            resources:
              requests:
                cpu: 15m
                memory: 250Mi


    service:
      main:
        controller: main
        ports:
          http:
            port: 2283
      ml:
        controller: ml
        ports:
          http:
            port: 3003

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Photos
          gethomepage.dev/group: widgets
          gethomepage.dev/icon: immich.png
          gethomepage.dev/name: Immich
          gethomepage.dev/weight: "10"
          gethomepage.dev/widget.type: immich
          gethomepage.dev/widget.url: "https://immich.${SECRET_DOMAIN}"
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_IMMICH}}"
        hosts:
          - host: &host "immich.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: immich-tls

    persistence:
      library:
        existingClaim: local-volume-media
        advancedMounts:
          main:
            main:
              - path: /usr/src/app/upload
                subPath: immich/upload
            ml:
              - path: /cache
                subPath: immich/models
            postgresql:
              - path: /var/lib/postgresql/data
                subPath: immich/pgdata
      nas:
        existingClaim: nas-volume-media
        globalMounts:
          - path: /nas
            subPath: immich
