apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: media
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:EdZwCEwWn15A8ek6,iv:JDwbASJNcIFRIFC9vf4JRNtqg3XomctRFmue/ZzkZOE=,tag:FTdC13tU7Lv+lOJtSw4zqA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:1sCKO6y3jbKI3OBgyUDLFVHbEA0=,iv:/Vl8+VvyK3iJDsBvqJ2SSYYd49FrncJ8AUvWldE9GNA=,tag:bRshIh90lHENbcHqOQzxuw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Nx8YqXyKkP9bna2SavuJFN+fmmMAZVBVokjwCRKCcdWFVJJaKIVZRTScd6BG//Jpf/GU5uKMCgA=,iv:YS05LGDjRqdNHf6O/GbHOsr+OMKPS+IDQWvsN6FGaFk=,tag:NUv/mXwZIH5rt0sZAwY43Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGh3bGZQQThxSHVtRjNH
            OVlsZDhsblVBRHZaOGpnaXZlRzZScUNaNmtnCnFtbStrTW5oek9nUFBoUTNEYmlx
            dU1rb3NLWjU2OE9oSFJ0T05NU0ZaQVEKLS0tIG12K05UakFuVE5hdlQ0V2UrVlkx
            SUpEbWg2OW1ZZU9jMkEyWG5qUXVwTXMKH5a1FDQ75sRu1wC6DWZCKBo1fnRY0YGy
            RL55yPCbts0UnG/2HcsgFIHrXyVao9YlGZ0utCcOlibofFZqCFVU/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T19:59:27Z"
    mac: ENC[AES256_GCM,data:BYvPbT4DKmiPjcmBluuMZUdnQ1+9+2ZJKSQZah0NKkZg2V504j68VJfKgoHYWHrntryfsaL8j4HDPJ9TOYtolJceZOl2TTJkb2ySiz1PjwOkfAF3RTmMBo5XVCthIG4F6KCydIYMay/0XAUHvMJLI3XoDGVVe5EReDi530tYQtg=,iv:zM7CIax1fTpKhs61Fy+REGX/2uqiySPOsLuNKKuEYSU=,tag:oxfAnINsnz11oTlGt18ZUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
