apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:HBSCr9zGOQ7QMEZnxjuzl2YcNYQapLP156JZNkO3h/O4pKzOL+xENg==,iv:86Lx5DhRHvfvK54LEL6xyo2dScxnqv8c0sfYFtk+7gA=,tag:6TtdnjHIYpNeFjGc6w8TPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbkNQR3hiUHRGMjdrbDNS
            R3lHdHV5R2lYQTNJb3VXKzQ5WUVOOThlRVRJClJzaHlhR1gzNTJzL0R0REMzYWtU
            TU9BWklMdjcwd2U2SnVTMVZwY2lDTzgKLS0tIDVtcWpXVDMrenlHdTZVYUZncDlr
            dVlEV1NFUTludUoyMEtWYWdWdkZ4SlkKxdqEDVxOg1/E4wKSEJC8NPn+SIL6JISR
            ErpPR1aBeVGTfiyJ2l8p7NtP+tko59xWrMTbS9ZO07E1muW9S+qDJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T05:25:42Z"
    mac: ENC[AES256_GCM,data:VW94T4TLD7RO56MEyPYSX2L2uBNHAwXKOeC/lj3V/rHC/jEU97wQt+rcl3ArX04HSDBBonLPEbgz3Nzw7C/+iSRVb0eLw6LNx8QLU9Z1wWOfPPKoaR+Nqa7kSsPoGaFftzYANA2gALOHxBSmAkzEB2znaLfwNAU5DjcyJXB98Oc=,iv:3oOabHKHF+Ef5+/3uLMVjW+MucnY0C4KYnPIhORnzFg=,tag:7zIFsgXukZgs3gw2nTbvLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
