apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:hc/Pk4NPlX5xh8RjrbWCz98VUbBm6xpRoBk9n52Xy0FbsTbI3D6EKg==,iv:USyx4EL9LymBj4Ov+bIHbNZ2yRMmjwEDGi/+AjiSQe4=,tag:E1yhPwerR1t3gjOhfajMWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTVMvaTl4bzZnVm5mTkpK
            ZlJxWWlsdktLNFZYUTIrb0wrV0J5SldvRUFZCnRUbUJnaHlOdkRzVC9aTjFTTzlr
            dHYrRHBxVmQ0bHlrWWpsRXRpUmlsdEEKLS0tIDkrUDV3OVJ5MkdvTXZIZi9SQjBI
            NzBpWWdBemNaUExOejI1Wld0OGlYZk0KCCRU9/XsPdPkDaUjjDjHZuW07eMyeAXX
            CSeibKtTmcDiyOLWZkncLm19Zwi4L/lnbEC1mY3oQTeVYKYg4NHKaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T20:30:44Z"
    mac: ENC[AES256_GCM,data:c0c6e4d+VZDwqikUBtcNm67eCAHDA+8tsdqWKJiaSgVdYLbWTZIc55vgErA/H9O+PVVA+16ju77xYvjkIB6tXPDqJTu7uv68e0r2Q4v7j20jsBvYnLO3LgsbDmR/Sv6p6+DPz5ZmPXbmuKjWbqjh3v7xmhUw7naEVJ3oh+qtvD0=,iv:U6uSKEBRQT6pIXpwsuDa0yp9DblelstsQrWUn8SG7+g=,tag:qmQ9kKdZS15ki1ko3YglHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
