apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:jaAeShabrSXeeyIjeacZ+rU8zsHDkIzIlPC4qeg1+CFgxOZe4janUg==,iv:DFn3jFb7CcnOIQn8bDrohic4yXtDPdjv2luLi29ln/Y=,tag:RKzWhlDWrrs7vg2ROsdgDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMlhIVFdsK2xSZUM0RlZk
            eklSLzRDRyt5bC9pSWUyd014Q0NqQjJtMTN3CmpwT2ozRkUzSzhEbkRUOTJNKy9l
            dk1VYnlJdkFJZDdaUzhzT3VEU3Q1TnMKLS0tIFBObmFXTnJEUjE2MTRhdzZXbUVp
            S0pJd2VCNzhncWhlN1VsT3JCeTI5aU0Kvp4wAzHBpU9EE8Ztyve2zRvhoHsL2uF+
            MtTrU7okaNaC3DZT3aZJQN4tSoSkb4MfaGRJLtOQLYvadmUZ2yoVag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T00:47:08Z"
    mac: ENC[AES256_GCM,data:oZ3CjEXE3Cnfd+ntReuSY8VDnCaZCbh3Y8q+4HygzbugwDor6gaolCuSj+FGiJVieHIiF1IBi3N3HnXaE2oeeySvZ0H1rPdFAe4vE2O0XulwnWD8LnTfA80ORrgHJyT/2Ygr5zucMl47HTXmC144p+JIKj6rMLG/BDb9ws9XlJQ=,iv:VqGfR8Ux9s3+VwGLYTM7/HL3sEEqyl3Jupvie/VnUUg=,tag:504+FGTeRpOikRUk0BlKbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
