---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: openebs
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    localprovisioner:
      enabled: true
      enableDeviceClass: false
      enableHostpathClass: false
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    nfs-provisioner:
      enabled: false
