---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-typesense
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: docker.io/typesense/typesense
      tag: 0.24.1
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 8108
    probes:
      startup:
        enabled: false
    envFrom:
      - configMapRef:
          name: immich-config
      - secretRef:
          name: immich-secrets
    persistence:
      config:
        enabled: true
        existingClaim: local-volume-self-hosted
        mountPath: /config
        subPath: immich/typesense
    resources:
      requests:
        cpu: 5m
        memory: 250Mi