---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: snapshot-controller
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    args:
      leaderElection: true
      httpEndpoint: ":8080"
      enableDistributedSnapshotting: true
