---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app joplin
  namespace: &ns self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            dependsOn:
              - postgresql
            image:
              repository: joplin/server
              tag: 3.0.1-beta
            envFrom:
              - secretRef:
                  name: &secrets joplin-secrets
              - configMapRef:
                  name: &config joplin-config
          
          postgresql:
            name: postgresql
            image:
              repository: docker.io/library/postgres
              tag: 16.1
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config
            securityContext:
              runAsUser: 999
              allowPrivilegeEscalation: false

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Encrypted Notes
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: joplin.png
          gethomepage.dev/name: Joplin
        hosts:
          - host: &host "joplin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      local:
        existingClaim: local-volume-self-hosted
        advancedMounts:
          main:
            postgresql:
              - path: /var/lib/postgresql/data
                subPath: joplin/pgdata
      nas:
        existingClaim: nas-volume-self-hosted
        globalMounts:
          - path: /nas
            subPath: *app
