apiVersion: v1
kind: Secret
metadata:
    name: joplin-secrets
    namespace: self-hosted
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:H/64sr1UThKd/aCd,iv:xjtgv5PdO7pUOiRAX1gU3T2oFYMjHMZyY4DLWpB+s7Y=,tag:r+Pd81QEz7KX/3eAypx0ew==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MVlr4/qQFeLAclykAUAQ4w7DEd0=,iv:DCD4MjpxcIcSEmZx/0WMph6NiNawt2L1D+YTB8vtLxg=,tag:xA/wLwetV3ztxgRYX8FT6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNTBpYUpzaVRzUVJGMmtr
            S2h6Y0NXV0RWemJyR0hiclRhS1hvUUkvcjBZCjZlY29BaDkvT0FjTE5FOWMyQUhj
            aWFEME5YN0ozQkR2RlJ0RmtKVVlUQ1kKLS0tIGx1T1FmQ2dqMFZHakxXcHVwbzkw
            N0xPNDljWnVBcFNya212MzJuWEdjU2MKZqXt7o5d1/e0yFfCbmlzTWuzaYoDYBLk
            fICaoAfWvIOmeuWeAwlD1gocyzAfyFjInpwCleU4lyc+PbwfkAP/aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T05:39:25Z"
    mac: ENC[AES256_GCM,data:C3HeTpQGP9oKBQ+ynQPn75r5SIYoEgZL5DJKXdWR2AYJpeCl9+RTQvjNPqOxY/1ouhXotBDfSwOptW3mAELJy8W6nKUelosut0QcMn8uodKTVG3FlwqtPsleqKE8G7golTo7rt4nXTemVi33D6o7YuRriOssDKK00NTjrJRkN3Q=,iv:LUmDyvX4A0I4n5R+bxMi1qM+8Z3fx7TSjwhbFLNjmQc=,tag:T81z1iYTD0R9HCPpbdnBbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
