---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-csi
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 10m
