---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-superset
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
  path: ./kubernetes/apps/data-platform/superset/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
