---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app glances
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: nicolargo/glances
              tag: 3.4.0.3
            env:
              TZ: "${TIMEZONE}"
              GLANCES_OPT: "--config /glances/conf/glances.conf --webserver"
            # envFrom:
            #   - secretRef:
            #       name: glances-secrets

    service:
      main:
        ports:
          http:
            port: 61208

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: System Resources
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: glances.png
          gethomepage.dev/name: Glances
        hosts:
          - host: &host "glances.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        globalMounts:
          - subPath: glances.conf
            path: /glances/conf/glances.conf
            readOnly: true
