---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app glances
  namespace: &ns monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 65534

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: nicolargo/glances
              tag: 4.1.2.1
            env:
              TZ: "${TIMEZONE}"
              GLANCES_OPT: "-w -d -C /glances/conf/glances.conf"
              # GLANCES_OPT: "-d -C /glances/conf/glances.conf --export influxdb2"

    service:
      main:
        ports:
          http:
            port: 61208

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: System Resources
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: glances.png
          gethomepage.dev/name: Glances
          gethomepage.dev/weight: "20"
        hosts:
          - host: &host "glances.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        globalMounts:
          - subPath: glances.conf
            path: /glances/conf/glances.conf
            readOnly: true
      local:
        existingClaim: local-volume-monitoring
        globalMounts:
          - path: /local
            readOnly: true
      host:
        existingClaim: host-volume-monitoring
        globalMounts:
          - path: /host
            readOnly: true
      nas:
        existingClaim: nas-volume-monitoring
        globalMounts:
          - path: /nas
            readOnly: true
