---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: glances
    files:
      - glances.conf
generatorOptions:
  disableNameSuffixHash: true
