---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-server
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.79.1
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 3003
    envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-config
    persistence:
      cache:
        enabled: true
        existingClaim: local-volume-self-hosted
        mountPath: /cache
        subPath: immich/models
    resources:
      requests:
        cpu: 15m
        memory: 250Mi