---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-server

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.87.0
            envFrom:
              - secretRef:
                  name: immich-secrets
              - configMapRef:
                  name: immich-config
            resources:
              requests:
                cpu: 15m
                memory: 250Mi

    service:
      main:
        ports:
          http:
            port: 3003

    persistence:
      cache:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /cache
            subPath: immich/models
