---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-typesense

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.84.0
            args: ["start.sh", "immich"]
            envFrom:
              - secretRef:
                  name: immich-secrets
              - configMapRef:
                  name: immich-config
            resources:
              requests:
                cpu: 5m
                memory: 250Mi
              limits:
                memory: 2000Mi

    service:
      main:
        ports:
          http:
            port: 3001

    persistence:
      library:
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /usr/src/app/upload
            subPath: immich/upload
