apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:+PCjlbYfZHidQkgYD0eHunjz3aLU7OKl1RXnoQWWODWDJPTZkIDq9YvbYPJOC7dzxaZHBdDTb4xsT6bd,iv:kIy9oYmBIfBLM4pgFzqMJj6kRl1g9cRppvR+fkVF22Q=,tag:EzExhzIunjr5Ae3UbBeqxQ==,type:str]
    username: ENC[AES256_GCM,data:jkrqDBM=,iv:Pc3f3VnmRD9BXHOt2ldgbAEVudY5wpTfyVJ13FqrdW8=,tag:S8FHU0ZmaKzpaF3DTX5ApA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdXBrcXBhSXU5KzVsdmFI
            Z09vaTNRbWdabW5BTFZQSCsyLzh1dU5NMGpNCkhZeG1nRXlJNlV4RTNrYXZzUHIx
            RkFNRnNqeVV3bHBpNnZ4R1U2Vm9PcVkKLS0tIEh3UHdScStjRXQ5eFNDU2dGSkZL
            VG1OZW5wNUxRNjl6RThoRDNTZTdCcVEKU06Ny56vv5d+NulwECvghXTelKl79orK
            iduFcDYmBi9m+0N3tTSndzqN6cjNndSyT3QLt4H+4gznYTIsP6Pf0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T20:30:47Z"
    mac: ENC[AES256_GCM,data:uA4sWLh7FSIt0RxDl9x37Ly1UwP8PCEQ88XFwWrCfutiKY6LyVtULmjYYdIG06Ce+YSFuWA3dEZ+sKxSsN3+Mu3Y14DK2TxLi3pVKlln7gT5ZAt+unb2pBkVlkYIIQPmV2rn2P4o6lhLrLF3UcIx5wgJ6q/gB7Q0QmwxbPw/qD0=,iv:q8BaSl9hp8iqKMK3U/VWs2sGQ/swHOKCjRuXaP4smvU=,tag:Ckdicq0OlsizhwozccH46w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
