---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-8

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: local-storage

  superuserSecret:
    name: &secret cloudnative-secrets

  enableSuperuserAccess: true

  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/pg16
      endpointURL: https://s3.${SECRET_DOMAIN}
      # Note: serverName version needs to be incremented or changed
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster postgres16-v1
      s3Credentials:
        accessKeyId:
          name: *secret
          key: minio_access_id
        secretAccessKey:
          name: *secret
          key: minio_access_key
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      volumeSnapshots:
        storage: local-claim-recovery
      # source: &previousCluster postgres16-v1
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster
