---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app influxv1
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: influxdb
              tag: 1.8.10
            envFrom:
              - secretRef:
                  name: influxv1-secrets
            env:
              TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            port: 8086

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Time Series DB
          gethomepage.dev/group: data-platform
          gethomepage.dev/icon: influxdb.png
          gethomepage.dev/name: InfluxDBv1
        hosts:
          - host: &host "influxv1.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      influxdata:
        existingClaim: local-volume-database
        globalMounts:
          - path: /var/lib/influxdb
            subPath: *app
