---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wallabag
  namespace: self-hosted
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: wallabag/wallabag
              tag: 2.6.7
            envFrom:
              - secretRef:
                  name: wallabag-secrets
              - configMapRef:
                  name: wallabag-config

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Bookmarked Articles
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: wallabag.png
          gethomepage.dev/name: Wallabag
        hosts:
          - host: &host "wallabag.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      images:
        enabled: true
        existingClaim: local-volume-self-hosted
        globalMounts:
          - path: /var/www/wallabag/web/assets
            subPath: *app
