apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secrets
    namespace: self-hosted
stringData:
    SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:aPi0RHWgbxyJTqt62II=,iv:8rm2CldCEJLBnOmtrCwL0iqTG15xP71b3Tirhxq8SSA=,tag:yNT5DilBYhx4Upjtb+c0lg==,type:str]
    SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:eHUKYkIUdD7dS0OlqdYkuhyD9Nv9xg==,iv:Hhns6Gz7U4J5948yUAcYMmiD4u0dl7YO6Df3+0AoRAQ=,tag:cd8ggUB0utzmRg3/RRW0Rg==,type:str]
    #ENC[AES256_GCM,data:KMnYMbXoldM=,iv:nY27Ou6jpgfC5U77sk+//gtDsamJiHS84TlvnzJ4rbw=,tag:sLN7o6iVmo+CtWbDFuuWYA==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:+jpy927+p6Q=,iv:aBmr4OSxI0mv8SajtUXQpyB5qHGiW4q1ZwMVuXjPDqI=,tag:hTsPWorw7dbJRVgJDGn0pw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3yzE0SLf5RZD+vsxU4w=,iv:oV9Hld4PyvMsv1AA/qw80RGUnlBRfal5jYSdXL7YkFo=,tag:ELIDdtdbqOqhlU6CoLjB9w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:EXJD5pFjsV3kvnJD8cTtjrtACtdgJg==,iv:ImlSBS9iKv6Euq/l5BE9y75ZTwxBBKstEO1/yt/xslc=,tag:+k/h9GyeqeeDLl7x7hPKPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVBxRitBNnlEcGN1VFI0
            b0p6SzlxOVBIYXBDVHdCblFWUlJINEZpd2o4CmppaFVNOFMvTHF4TUo0MU8yVE1v
            VnRKL0NQKzAvNmhwSCsrcXRxT3hGbWMKLS0tIFpyZ29FZ01ZTGp1UnIrd2dnV25C
            UGRPWnRDeUJsdGI5NHRwUzVyNjBTNDQKo7c5dCiNtNkxB8FcSirpbqkoKHAowdi6
            EJgCP7f1TcFJrCkVNTt+VMMIjUFbrqcUDkZ+EZMdI2s0JchMVj2Fqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T01:58:08Z"
    mac: ENC[AES256_GCM,data:izoXwJ5K9UFxL+Rzaty3qfjXQ9zA80g9ORTwQU+p1RtpNLbXEEQWg8LV03CONAzXaj/TkMf0ewEqmZbDpJZCZBCblX+IkyksSMAcrK6KfIxlYYxm1ezGg55aOvY1AcxCXWbnpbgfCGWqrcqdMWlLneOs+afwc2578pitsUiN0HA=,iv:fUE8/e17y6z3fWACe+5ui+CD7XPbJT/CBlNIUpIrx+U=,tag:x9VtsTSdZMnyR2onD9Jg4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
