---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-microservices
  namespace: self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: immich-server
    - name: immich-typesense
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.81.1
    args: ["start.sh", "microservices"]
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        enabled: false
    envFrom:
      - secretRef:
          name: immich-secrets
      - configMapRef:
          name: immich-config
    persistence:
      library:
        enabled: true
        existingClaim: local-volume-self-hosted
        mountPath: /usr/src/app/upload
        subPath: immich/upload
    resources:
      requests:
        cpu: 5m
        memory: 250Mi
