---
apiVersion: v1
kind: Service
metadata:
  name: datalake
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocal: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: datalake
    role: primary
  loadBalancerIP: 10.172.90.57
