apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:0IA+8lMjEpC7ZWNq,iv:IssYKEcJAYEfcYVAv0LnKUJbsuKTA0V4RzJdjXIQ5Ig=,tag:k8Ra7DUCPre+HQ1xwBMaog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUGpnaUtXZUNNclpwOWdp
            U1gyMGxNMHNScmdqbFlqODRMeEZLUnFPZEhzClk2d1ZwSkE4cDk2bENycnBFazFV
            Z1VzTWhWN0laKzlyVGx0eHRvd1JIcE0KLS0tIHhPK2NKUlZmV2J6ZFlDcVArL0FM
            MEg3dmpWNjhXV3g1T3ZKS0dWVEY4R3cKMSeQKXIVhGL09eRQma39MTJwmT7hyltr
            Ks8N4bxBQneryjyBHTYippQyRCYQOltf7/9JxHIgmyauyuVJOquZRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T02:49:12Z"
    mac: ENC[AES256_GCM,data:JrEyos00w6Dy4UfstG7EyiNfJw4yr2T583qTJ8839DO0Y9xfuwKSP961l4gqkdORN2LlCCgTg2XlWgN+fzIleDbIrEqgFTJXxP7DTYleJh70VzJIT6Ctcwhln6LXxcHPyceadQMeQL9o5d5cMfPczYK04SQsp1GNMP9Ayz62uyk=,iv:JrihEXtel1FCzXlL53XK3lxhdqKmG8LmlnC8JumcptM=,tag:Kv8QyHnm7KU+h+nJRc+iVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
