apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:GuOHYjh53As3yEKF,iv:zyaiONzCemoLYaMSrjoj3YYFdMmg0Q0pjrOina4MFMA=,tag:23mgbxZAovGMieppGs3sYw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AWviJ6Iqm0iGLhJJY+ilAksaDvc=,iv:nvDTHq5/3dlOo7G5Kh7I/6pMOlRsXHEEeiv4QcWpsCM=,tag:ojva1RKGxozgzOYIa7Dqsg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:NRVhlGyOcTD8Z7cS,iv:0CsB86N9rzwjYRUlNpyeRVICjUS0e5e0Sl5RfH3BQp8=,tag:aRru1hhbx5B9KSGKS7SQDw==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:0PxBDE5IbU3pTyfx,iv:ytKVOyVG3pzT95dlV1YiIOSbBQvQ1CR8S2K7eRbIdS4=,tag:kx4oeQxkc9eZkNUf9zbhsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N211dFZ1K2djdURqYi9m
            TEtyNzJ1WkJEYkNQQ29WNGxLQmFMeUNjcVFvCmUyNTAzYUZJdUgzSzU0dk0wY2VR
            WEpTSUJTZTkzZ3F5MDRDdDQwdHZkd2MKLS0tIGZzdmU3TUJ6b0lCd3JHRDduMXdB
            N2V6RTZQcXNlZW8wNTBFOE4raWp3WlEKco3DJBHqPwqDhJzzCeLCsUxLzXLY4cw8
            hyf1fwN8kYXi8pXoH/7mzgxmp6Ct7y4mEFGQv4T0paFbaiEbi9OhQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T01:44:54Z"
    mac: ENC[AES256_GCM,data:8dpfJT5IyhMJVQ/HU2VveSxr+YAuXcva+AeiFGkaiyDrdPaAnHQS0ODbZ8SV1vv4DAOWWMCVsQi3eYZFUtvWX8aT3LVYm1QfMLPnk83fAHHv059ipFaJPgMajIn6p6mHPCyF7VRiLAJZoQ/Qq/whkcFgJZJhUkFFdeSF/JeBpfM=,iv:iosLpADQ1yDJK/bb9I8ae6x8qkU8VHYGaLHGBdTSyVc=,tag:If57i5XA1dboiHac+PvPGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
