apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RsAWTNYX2FBDHeoz4VzkV2o=,iv:PFz96G+LxYbuocetODXQw+f87G6KkNl5W/LEJzXBxKI=,tag:UZxQNMjxv3yna1xAJeY4uQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:5h70IJdb649pkBc6lOY=,iv:3AKQhQ6cjvysDOj3pb8aTyIKZ+Ls+doi+8+rkConR9c=,tag:IpeY/X0BgSqOsDCOErxa5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNG1kbEZOWkIzZDJtYXUw
            Z3ZvWWt5U2VXWkVtczc3Mkw1cjc3RlRuazFvCjFYbVBCOHIyeFQzdTVOM3lxam9S
            alg4RHpNb0ZiNGM4blFIVTBzRlA1V00KLS0tIDV4MG5KYm1ma3RRZktYY1grQ3lN
            U1QwbEdBRTFpZ1BlL1VMc3NDUm5ucXcKtBkV+fVNTOmDsoqI3mWYC1i/7qhcMtfH
            xtqtvi6swXxi9o/Q456VXRCaGnwIiAKQpcPRr6eMdZglc2TIzD5HMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T20:30:43Z"
    mac: ENC[AES256_GCM,data:fU/NcXUYSWbbzk4W9WpE79K8QR7SAtVowrS9H7sdmhMy2RoOKwNrDpXn8+7lCb92ONylpJ/FCvmSUe5o/jyY8aL4Pi15dgHYgV8SXIZyM+DV1A5EGLacFYYV/VkFtAVSWXzzTkmRM9VAdpEQbm5sAdhqGQxY3yNob8UCpgHm5yU=,iv:ZTZUqra15SDyw+/tPrnkTuajpBqMrxBTHTJVthM1vn4=,tag:6uP6FXMBwDGy0I6FezH+3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
