apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:K+j/lMJjTj+AvVGN,iv:nG4YmyVz7vIEul7QzIVW1TlSaafNIYitTOhYfamFydE=,tag:eBPpChGckfMlRwqmw2EHOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMVJza2RSSytMRG1RTWZi
            ZXhIZTM0YmVqUXZlczJvZit0WEd2SWhJR1JNCmtaaWNYZS8rTUUwdmp1M3FRYVhV
            WWNqaWxwVlMvMUd4N01EVUlJZnhUdGsKLS0tIDd0ZFBucVo1TStNaThoVnVqZ2l2
            RllvZGZIWTBMWDRzK0tWZVcxdTI1VkkKlOZ1YVHxlIBaTVShR7qJRBcJaYCFlXKq
            CP1GKIWdodkxxfslT+KNQNghcL9qsjf0ANw4gymlTTmhLkG6pMXD6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-21T02:01:45Z"
    mac: ENC[AES256_GCM,data:TNCUs6aMI07z1VJAi01DVZyOECrKSRRwmJb9ZWzr6onB3WCfYn7bty8rLlnFeWVgWP2KT8KCSOuMFnP4wGC9ialUyNCEnSn2+aLUWFa6k+b10RgF3J8L1iYL9NwppkfHgKiRm9s0GV64eUoUuvgqYyP1DxIQT/NbYvzVSE3Ge3A=,iv:XOh2Cukmv2dAK6Qem47Jfd6lGrulyHq+qYQIIvDlqds=,tag:5wGjjQXkbDD8GCbTWuu34Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
