apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    DW_POSTGRES_HOST: ENC[AES256_GCM,data:/xIpotR/vniI1Q==,iv:jKqnnP2dNRlGz85jKEqDcChqSOd9v1cf72JI2+2/nZc=,tag:olbrwuioryOLUF9V56ESXw==,type:str]
    DW_POSTGRES_PASSWORD: ENC[AES256_GCM,data:MtE6SzYlooMb5mKVopmrbFaVPIc=,iv:ycrju7IC6HiNYZQWl/GP40Mw0w12etrnj1LBcvV9ufQ=,tag:ACfdjgjgzMFaQDHMMQGURw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:hzREhhjP+RNqrg==,iv:KZcY44setVYDZFk176CCqJe/ErmNoDaptQA3l7ZMRto=,tag:p9tyUjowsW02rQw4i0klVg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yr0vs+wIxlnRJFvSSaKfQ1/YtSU=,iv:AC3s++UGlZ9zSgyR4IsjljA+Mp71ALE4Dt1RQamsZkw=,tag:GBk5Jc+/FlxPOiT5BZiYfA==,type:str]
    NATIVE_PG_HOST: ENC[AES256_GCM,data:2ZMPo8LCjbT/5g==,iv:qgCBLyNeu2fn2qXAfUhvfOYZv5uWhyM1ANaUiNnHhmc=,tag:ktkbhVBwD39ieNQg28WNKQ==,type:str]
    NATIVE_USERNAME: ENC[AES256_GCM,data:KQEGT59NJLA=,iv:krwS28ykKuAr43uIFcR9sRzjSs3zc9uqLdqUtClOHeE=,tag:x7Rg8c5xWEj0aakwpaBXJg==,type:str]
    NATIVE_PASSWORD: ENC[AES256_GCM,data:aKMxhnDUtDAvy55AmuzFtclRKU86RQ==,iv:hdDwyYHZAK+VN+M1yUnf5gUQDZQFb5iyBNLpSrLTaM0=,tag:lEy9Aeh9scXIWKM80seLmQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:AlYeFPEoIqITOwMUQQ==,iv:tpnZlDMlrOmzZSDiKKd09634NGe3zLu1yU/g4TeS5OM=,tag:fxLTy6d7XVO89q0EhO/l/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNUhhNlQyNk5CaHhJQ1BX
            VGQwczc4Qk5WdUpyVzl4Z2VvWGxJeVdkOW5rCi9aY3FTd0FDR09sY3lzK1BOT0p3
            YUVQSjRFMm1HTWRWVDBrc0xXdFptZEEKLS0tIEFublZ2Z0V5ZXdZVXFpdkFwRUdN
            UlA3VEw1L3NqenR3VEp4d2lrWDE5UEUK8FkuDV7SnAipjL75JwzE8eU0X7Eg35Cd
            QF1C70YkHkKmbKJAxUBBNxqxveRuadqm8eOtG0zDflW0nAkfRBT+Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T00:24:37Z"
    mac: ENC[AES256_GCM,data:4b8LHwc+o3Ln/kH7uzc0001ODD+3Ndms4C5LtC8LV7gFgto5bwn4wZ1YxJ5PqFanL1jDYnurTzzcYBQ30GdXYtDtUUhgBJU/pY79GhFZ3EZF1rfBkd4zKcKDYDsBEJ8mQB68O7N9kEIFStHOdR+AvzCCf7Jbi9u3w44T5sGIK7Q=,iv:3nDkM3XEqagSzQCzxYThL3CJBW91qyVVfcBj0RTUxGI=,tag:XhlE9WDedN5ol4d7WJ/8sA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
