apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:T6sqzPGNsKIe5b67,iv:Nk4RU4hchXm7bPbCbx0rNJ3a7dh/aaiPe1OVt3ARplY=,tag:vSZl/ft7L18JmwAtp0ASHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK0YxN2xIS2pZRisyVVpC
            SVpraE44RzN2eVJpQUZVUmFHNEk5aFhYRFhrCkxBWkV5Tk4yWjF2Y21ORC9TUWlM
            Skc0Mlo1TXZwbWpWemdxcGcwOE1QL0kKLS0tIFJ2SWUzZkcwSkdualJYRzNTanlC
            L0U4Vlp2SFlPR0c3K0JsWnBUY1MxNkkKvFz/xKfL5qgDYsh58U8OaCMuOw47jmWL
            XA5PvurhaYcEPKv5uvaKHnfb7Juh+0bEXF7wpGYLYROOM5y7aYhrTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-21T01:45:28Z"
    mac: ENC[AES256_GCM,data:e1uxCQiiu28I+hYQHEL4QRBJpqxLUAH8z8JxYFlJv3wgo8RChmx16KK4dcNcn8cxD7mDzlp7Zjy0LHIC1ta3yIvQI0MbFDWsgS8zxS/LC+WgMdsVGqvkA1nLzT81Q3gi4+3Txy/VN9EzCSI8QspToCxJy3SLxQkwmULnBmuYDPU=,iv:NE+I+7ljhp/PbatUcEEqNlZriGyAnmebOz1l1pTfJGU=,tag:qKtMub1Ted6f1mT2JkARdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
