apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:vAxoAfnGB2Fd+Ehd,iv:Q+TmwK5xwZeVyVwubn5u+8jWNf/h+YmELiwNlTdSs+w=,tag:Ibi4vvAr+BnQoa1ee5LswA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OHR1ZUFFNFRLcmFBVFBx
            Nmh3QjFES1c0d29DMEV0Y2VGWUhvVFVtVDE0Ci94YzUvOW8xVnlxSDJWdE5NY1Ra
            UjdjR1lRd3M0bS9BOTJCaFFNdG01Y2MKLS0tIDZvSkZqdEJ4cVZEWitIWFZEc09I
            eEt4UUl2R2ZYKzk3S3JzNitQVVd0eTAKsrdN8tEGlp4G8CAXbk9ms4LWMmlLeW6A
            wSwJHKn+v/cMwgtghZWN0t7kjLucG9O/EFAY0BrAfBpAGCUqUnOJuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T01:39:41Z"
    mac: ENC[AES256_GCM,data:kyZsFBb9oa1q9833t4VxhLk3Vktu7pf9ye2HpPhbAMU5rVRDB6wxfsrMn8U6zhp84NrmlF5DJ9yxemLPrPPkAAhV7cFNgEO/ZMvarn/lqHMCr5w+TsPoS+6pXtketCKHGdUkrq/xayn0rT/TKCpHWqC7CfmIZPT1+m3ksZeS9ho=,iv:Ws/nQyZKwU7Dy3Ikeuoh4gaXoDwmiYUzzS1YxD38jXQ=,tag:3EP7ehC4OW0OvDmYcKQK3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
