apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:w2KTpNO1IMsuvyRoC9Ba3Xg=,iv:Vp9WFgsbBarEYKLDoOCZUWH1hIXTxP8vQqvwWhAWvzo=,tag:KmepKCx71Toe6RhjYm/wvA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Cvrc4bo+dJ5WzqAuJJO7BhoHpcUk02SRm3MwOZkCpXgm0J4C,iv:RAHUKCoEa1CFVvvBoQ8hKPuJ6iPaj2acwTKoWBFg1ZI=,tag:zospIMQkB71ThoTaFL4N0A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:tiJNTeD/t68zwhwMuvU=,iv:xOQDpYDj51kKkUPH/NosWLVCmBpswek/hmVgx98/YXg=,tag:WUONzV5M7U6LxT0WOrMUzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S1pKVm9jaDh1WkhIYU9l
            ZTRFS21zWmgzYkxFdG4zVjZKVlV4NjgveldJCjFzVnNqT1R3NlA1WlNBM094NU1I
            aWxXK2R6azY5QmZhaFQ5VHFKQ0YrTlUKLS0tIFkrZ3lHWFIxMDFZUEphR0JWT3I4
            K2dQQm8rNnMzUG9JcXB5SzZ4RldSMkEKcV6lojQb5YDIs5BrB/qATGPmWYOKnDGE
            tbL2PoWb9bJvrObyfdxFa089pDf2gSAazhMaXn+Y8HG9lfxAKWjcuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T06:22:37Z"
    mac: ENC[AES256_GCM,data:9JxZoOZv/ZeUnJaVoHbPtHiOJPzEimZGhQGfNKQpNifqWHl19m2KDemO1vj33Cz0gt18J/PlIPRh7LoqUbTjSMRuDbvPuxr4Bh9LQLir788USlC2L71h33Yk22QKoeMeKxRZ4o3sXZk4ZDkbXSvy30g/fZUBBP/63kBZ/e1a3Ow=,iv:xaaxUrUMfTNVMiYxrPbykOJNEmy0sqVG3lu2DJNOp48=,tag:AXG4S+je3q6J7raVbr1qvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
