---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/West"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "10.172.30.92"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.172.30.0/24"
