apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:+QAvUrkeY9rtCrp389CJoPM=,iv:Qfa5kj3ztn/ZhB7vDAXHMJklmsdJWqbMm4TPIcNGQTo=,tag:9daZDxaW3x//dXjd3C2sjQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:R1/np+XqLl9sjHwaDhw=,iv:prImFXIOyjePN21wxAWZvQ5Ur6SCFCuvZFhEyelODWU=,tag:EwjR/gYhDUOaw1QESjBz+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VDdtaWd2ampoR0RDa2h2
            aEdEZ1h6UmpqbHVHaEZVSHE4NjVLSXhJc2xVCmhBNHRQbWdzZ29qQTRZaWh1eW93
            b3lkM3JoR3R3S3hINzRmNXN3N0JBOXMKLS0tIHdEVDgybE5BOGtnRjZ2WUFMZGc2
            QU4rOXJYaDhwbHFqTXpTOEE1R005bkkKHIF/tEx3lPuWRuKB6/A0TgRKbXSa6NEq
            KbHRYcTKQTdWp8FPtiTjGQI6+X2NHsjqFtvTpSDP/31RaIYKeE6gqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T02:49:12Z"
    mac: ENC[AES256_GCM,data:RcqkskII+UgNoaOUmZyDctD89NtT9LjVSaoftid90Llvhq59jx8iuuowXdCcTgyLSLZUB4JKqJUNc4YMnYPP8jQ6Fj1p0Q3HVZQzhMVhuDdz+XubORWO2yt48t1HGkGVTXCZ+FrxbHX3mjAE2kn9Ow0c7I/QBKuY3EvDfn+QgVc=,iv:Buul46hBKYM+wUSLMQMAeKw/eCga22Cm6XY8nqD7tVk=,tag:7gNAAzcFZVpFtlJAa8/A4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
