---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: &ns data-platform
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: 8.3
            envFrom:
              - secretRef:
                  name: pgadmin-secrets

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: PostgreSQL GUI
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: pgadmin.png
          gethomepage.dev/name: pgAdmin
        hosts:
          - host: &host "pgadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: local-volume-data-platform
        globalMounts:
          - path: /var/lib/pgadmin
            subPath: *app
