---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: data-platform
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      replicas: 1
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: dpage/pgadmin4
      tag: latest
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: PostgreSQL GUI
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: pgadmin.png
          gethomepage.dev/name: pgAdmin
        hosts:
          - host: &host "pgadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    env:
      - name: KUBE_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    envFrom:
      - secretRef:
          name: pgadmin-secrets
    persistence:
      config:
        enabled: true
        existingClaim: local-volume-data-platform
        mountPath: /var/lib/pgadmin
        subPath: *app