---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 4.3.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true

    nextcloud:
      host: &host "cloud.${SECRET_DOMAIN}"
      existingSecret:
        enabled: true
        secretName: &secrets nextcloud-secrets
      extraEnv:
        - name: REDIS_HOST
          value: "${REDIS_HOST}"
        - name: REDIS_HOST_PORT
          value: "6379"
      datadir: /var/www/data
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
      securityContext:
        fsGroup: 1001
      podSecurityContext:
        fsGroup: 1001

    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "${POSTGRES_HOST}"
      database: *app
      existingSecret:
        enabled: true
        secretName: *secrets

    ingress:
      enabled: true
      className: internal
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Self-Hosted Cloud
        gethomepage.dev/group: homesys links
        gethomepage.dev/icon: nextcloud.png
        gethomepage.dev/name: Nextcloud
      hosts:
        - host: *host
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      existingClaim: nfs-volume-self-hosted
      subPath: *app
      nextcloudData:
        enabled: true
        existingClaim: local-volume-self-hosted
        subPath: *app
