apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: self-hosted
stringData:
    nextcloud-username: ENC[AES256_GCM,data:+K7CHzk=,iv:c+VFKWP/mFYZOvWxxRoeM9lJgDJOa9a5Na2TSzTsEUI=,tag:UhX3h2zv/UccwPEImuVPvw==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:/NbJks3AwxRUK0eTXcmRg+rbv/w=,iv:rSoewrJNfyQE/GOwQgE+lQhGingTI39qLO9LNjiwyVw=,tag:9K2/M26rzrt9AuTpPf0odQ==,type:str]
    db-username: ENC[AES256_GCM,data:Rvz9H0wcn+SmO1zsSvUu,iv:5PHI0G9QsSCkYV880466BZiyHNBf9O07sK5/58SPIRY=,tag:3W01VlLBU2PpZXxCITW4jQ==,type:str]
    db-password: ENC[AES256_GCM,data:jYaCBocOnhxebFJjKnEC73V5Qos=,iv:XkW0h7q+8Etol+3WOMvJUWZioBGFK45GVX8IWUHfEFg=,tag:0j1MoQFTUs25L6xUjHpFDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2k1dVZZbTczNzl5anpr
            cWFWdVU1TE9ibExOanZCbjkwZCtQbWZYemcwCmtKNlJteGJ2UnYvWDE0QitseVFY
            Vm96dFFndFZTTi9mZnVHM1BVSW1QQlEKLS0tIHZEOGw2Y2IzQVFBRDBlQ0F1aU9P
            cWRkTHdKTzVqMTVmODNYQW9sYi81UVEKgDbYyzfWrUpp26lWgj4tnBNv0gbVF44E
            OZXVAmUmb8iHdMyAd2dlCeJ20znmNrtzm3/jqZQuPsbWGZtVhCNF2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T22:45:32Z"
    mac: ENC[AES256_GCM,data:Js13of08AZhesLj9qDLNQsoQcXaDu/0Pr4cl76bAo9PRQo2Ppr5NQyXJhKXeje4AIMyy/HM5eMZ6j8BamMvXjMCC9md3DVGMkqG6l4gS0UG99Vr6T92ioz4w0RVSbLFZs65q30riqd3pNOLbY6CuwLKCypjFB9H3zdWJshjyh3s=,iv:7k8oD7QzAVvHTWNalvktvtPbkAExroy9Ty96mSHPy3M=,tag:Y5ZaX/4J0NWBk8fgHlwavA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
