---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mage-config
  namespace: data-platform
  labels:
    app.kubernetes.io/name: mage
data:
  TZ: "Australia/Perth"
  MAGE_PUBLIC_HOST: "https://mage.${SECRET_DOMAIN}"
  USER_CODE_PATH: /home/src/repo
  DW_HOST: "${DW_POSTGRES_HOST}"
