---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mage
  namespace: data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: mageai/mageai
              tag: 0.9.32
            env:
              - name: KUBE_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            envFrom:
              - secretRef:
                  name: mage-secrets
              - configMapRef:
                  name: mage-config

    serviceAccount:
      name: mage-user

    service:
      main:
        ports:
          http:
            port: 6789

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Orchestration
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: /icons/mage.png
          gethomepage.dev/name: Mage
        hosts:
          - host: &host "mage.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      local:
        existingClaim: local-volume-data-platform
        globalMounts:
          - path: /home/src
            subPath: *app
      nfs:
        existingClaim: nfs-volume-data-platform
        globalMounts:
          - path: /home/nfs
            subPath: *app
