---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mage
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets mage-secrets
              - configMapRef:
                  name: &config mage-config

        containers:
          main:
            image:
              repository: mageai/mageai
              tag: 0.9.58
            env:
              - name: KUBE_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config

    serviceAccount:
      name: mage-user

    service:
      main:
        ports:
          http:
            port: 6789

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Orchestration
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: /icons/mage.png
          gethomepage.dev/name: Mage
        hosts:
          - host: &host "mage.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      local:
        existingClaim: local-volume-data-platform
        globalMounts:
          - path: /home/src
            subPath: *app
      nfs:
        existingClaim: nfs-volume-data-platform
        globalMounts:
          - path: /home/nfs
            subPath: *app
