apiVersion: v1
kind: Secret
metadata:
    name: mage-secrets
    namespace: data-platform
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:/lvXPlO82eLKrjRo3g==,iv:9TcjBivCWc7LaYueI7SwNFCQNbjKq943L81z0QRKGJc=,tag:97vLC/X59Dj+8xOGC8t0/A==,type:str]
    MAGE_DATABASE_CONNECTION_URL: ENC[AES256_GCM,data:qsMfr+W4vq8aBzEugdWGfT3m8noYhI5mjINQ+nF1Xsnzxtcld5hZWLtVuDU7oXnXdfvl4QTrXksimnwiTQ2gWD6ILJ5uhmn7mQ==,iv:mY7pQAqokD6j8HXs7GPb809YE89DqN0rOFAlmzEYOeY=,tag:5OX1RW2d2gGUxFhcaa8NlA==,type:str]
    MAGE_DW_USER: ENC[AES256_GCM,data:ZmPtqQ==,iv:gk1eizeiF32PnCBd44m2MnAZRbKwxSFAhH0UArapcVE=,tag:wdReY0sY3dmYGxnEZn+dpA==,type:str]
    MAGE_DW_PASS: ENC[AES256_GCM,data:MEc2j/8yZSDb5y+y6/TFdoyJwnQ=,iv:S8PaucZeBQ0cweOUsrAumj12I7deBtKPZbjHg8vFcp4=,tag:21XYfdPt3JpKJvVNBn6YTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSGhYUDdLTEtRaGRLOGEw
            SjFGNGI0eURlV1oyd050YlU2RmZKM2gxRkJRClpJWmhzRWpxQWlHVUpVTkhWcDlj
            cFhlM0xUempnTXRMcUdqL2RvS2M4MjQKLS0tIEVHamZqS3VXZ2VBK0tkT1VhSlFF
            MU5BWnF6ZEUyaHViM1I4YnNBMkdLaTQKsE+2MfoDjW8ZG3/Ev/h4ZUf1ojaXqCWW
            uiMHejyTt1WME8E20Xmq1MRfaml7ExzlKBPGKObUOKS5dydVP4ENPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T21:53:05Z"
    mac: ENC[AES256_GCM,data:Te5wUPennqMiR6rc+Eov1CSbYvi+mJZSjd5Zmyjjdk590TbJbiAB4oO7+e+uBxhEqn5PsKCFajLpawKie+HB/Iasu0rLd7tHTGPuD7vU2/mhRmnyDAzzyM40ixMlHpkrSRH4Rx4CBPl/gwjuVehhw/b8E0SRB7TRD6XGwe598mo=,iv:S2hxigKqlYigXhc6ZS6+FnhHygWFSrr96aFOS67klmo=,tag:NZLSCDbyGZDY3dgYs+tftA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
