---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app datasette
  namespace: data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: datasetteproject/datasette
      tag: 0.64.4
    command:
      - "datasette"
    args:
      - "-h"
      - "0.0.0.0"
    podSecurityContext:
      fsGroup: 1001
    service:
      main:
        ports:
          http:
            port: 8001
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Exploration & Publishing
          gethomepage.dev/group: homesys links
          gethomepage.dev/icon: /icons/datasette.png
          gethomepage.dev/name: Datasette
        hosts:
          - host: &host "datasette.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: local-volume-data-platform
        mountPath: /mnt
        subPath: *app
