---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app datasette
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        containers:
          main:
            image:
              repository: datasetteproject/datasette
              tag: 0.64.5
            command:
              - "datasette"
            args:
              - "serve"
              - "-h"
              - "0.0.0.0"
              - "/nfs/duplicates-ver3_2023-08-07.db"

    service:
      main:
        ports:
          http:
            port: 8001

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Exploration & Publishing
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: /icons/datasette.png
          gethomepage.dev/name: Datasette
        hosts:
          - host: &host "datasette.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: local-volume-data-platform
        globalMounts:
          - path: /mnt
            subPath: *app
      nfs:
        existingClaim: nfs-volume-data-platform
        globalMounts:
          - path: /nfs
            subPath: *app
