apiVersion: v1
kind: Secret
metadata:
    name: kestra-secret
    namespace: data-platform
stringData:
    application-secrets.yml: ENC[AES256_GCM,data:RbIdnFflHehRfLlrl8v4gIiYvZ5xZiJggHzvutZ/hmopNHg6NL6tfw/XjsvnKtqWXluPee46sRmUcAKa3uzBiv03TPxxGllX8CZLSSvWDvNu32OQZnQuALUk4aAdmrjLVxjNfiXm5h0l6O/UUFD9GoSHHP1Ot/Bs7H2dhdGDzXoS/Sa4GZ+sM0XEKjwzdiUiTrC4u/CG92HwhJey5jZqBHMhttT6ZQcSNLcbrvVnsgoiw0jkySOtU2CfuMNY8HSfbIhIX5lanroL6XQxR+u5J4eWpu0D8hobFN6Bn7vVmpW5aCgUQkMKI0ZSJPw96yGtP4C74/KKzwhPu99dKqoUbgRaH9XibE+px5fqsuGLxifiNDG2kDJ2nqX6UoECn3aoYPm/uqvJ6Hgkoun4J/wp,iv:28G+Ml/U1LzDIObqQf5wWojW6GaqmXqM3fAEu2gWyvk=,tag:v4r3UwKV4A7DhYW3lVmkug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2pWQW5XVHJlMkRvUm1K
            ZzRVNFJFeTg4VE5WaVpHKzB4ZnpyVmhOL2tjClBFRDBJeGVwd1VXejFHTDhTbkVT
            WmRDdldsbm9FY1RpRytFWDFPZkVUU1UKLS0tIERyMkNRUEtxN0JSS1Y0T3grTHpx
            R21kcElkdXFZNDFZbEZCVHJ0eWdxd1UKdmgn0EDysEgl0Dn35JC9d6133R9ByzCm
            oMBqLV2pINDQ9xixqTRBjqxxPYDTdwxfFsWEvow63kZAQ4Tm+e3wGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T01:50:15Z"
    mac: ENC[AES256_GCM,data:EzUyXjugyeXnbtffIH/wZpuIvSt0P2uZklYK05zUYECILpYDsscp5xPa8tGzitI1QnOlFpeGGor4XSpw27tsfoqNNUQOSKTanrpwQo8ILdtSDmuKVCjohO/EXLOa0YUMul7GRZ3TrTboSFSevOFJUK9ZOOvFLIIdK9/evSpN30c=,iv:ro03lsCuYcNc1fK3SEYZLiGQ1W8Rt9y8VqqoGgH0Tmg=,tag:sLqvj5lGxsFuI0Pt8i7gmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
