---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kestra
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: &secrets kestra-secrets
              - configMapRef:
                  name: &config kestra-config

        containers:
          main:
            image:
              repository: kestra/kestra
              tag: v0.13.10-full
            args:
              - server
              - standalone
              - --worker-thread=128
            envFrom:
              - secretRef:
                  name: *secrets
              - configMapRef:
                  name: *config

    service:
      main:
        ports:
          http:
            port: 8080
          management:
            port: 8081

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Data Orchestration
          gethomepage.dev/group: *ns
          gethomepage.dev/icon: /icons/kestra.png
          gethomepage.dev/name: Kestra
        hosts:
          - host: &host "kestra.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      local:
        existingClaim: local-volume-data-platform
        globalMounts:
          - path: /local
            subPath: *app
      nfs:
        existingClaim: nfs-volume-data-platform
        globalMounts:
          - path: /nfs
            subPath: *app
