---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kestra
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: kestra
        namespace: flux-system

  values:
    postgresql:
      enabled: false
    minio:
      enabled: false

    dind:
      image:
        tag: dind
      args:
        - --log-level=fatal
      securityContext:
        runAsUser: 0
        runAsGroup: 0

    ingress:
      enabled: true
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Data Orchestration
        gethomepage.dev/group: *ns
        gethomepage.dev/icon: /icons/kestra.png
        gethomepage.dev/name: Kestra
      hosts:
        - host: &host "kestra.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host

    annotations:
      reloader.stakater.com/auto: "true"

    initContainers:
      - name: 01-init-db
        image: ghcr.io/onedr0p/postgres-init:16
        envFrom:
          - secretRef:
              name: &secrets kestra-secrets
          - configMapRef:
              name: &config kestra-config

    extraVolumeMounts:
      - name: secrets
        mountPath: /app/secrets
      - name: local
        mountPath: /local
        subPath: *app

    extraVolumes:
      - name: secrets
        secret:
          secretName: kestra-secret
          items:
            - key: application-secrets.yml
              path: application-secrets.yml
      - name: local
        persistentVolumeClaim:
          claimName: local-volume-data-platform

    podSecurityContext:
      fsGroup: 1001

    securityContext:
      runAsUser: 0
      runAsGroup: 0
