apiVersion: v1
kind: Secret
metadata:
    name: kestra-secrets
    namespace: data-platform
stringData:
    KESTRA_CONFIGURATION: ENC[AES256_GCM,data:3+gHtWxe54lS8aFMy4Rj3hgRuYTDND0w5nwWJVitZHToHVpvXGOEVrqx6+Wt0ek8Z+oFBTW5swYcO6ZZWMUgMvuuMKzDaX7onQ8oe1gGgaGp0wobT2f7tJNqoWhYWAdhp4dQW9GwORn+Ignf4D6G3FoEm5eeJgzsQADrGb/SsQNqHNle1+iQDCwv75FoRtrGlCWVrksPa8xmGCHuEISm5A9XqVbWiKHAzCqsUBETXgbkT8gog6ci3y4HSP2qeVlVZKyJ0vG4iNOtxd6Emi4tWPz0gIGg/fJiS+VbC46dXuI+PfKUJQgcf4SKaLsxYckmtSEb0pKkknWKPSTvxwKDFG6O4phAktDFtcfMAo4Mv+JjY1H3fwrdx1mU64RdWR/0fzghiXJ4aIdP6D1g0k+rSQDXhGYa+IRboS7zXguQ1+A28M4vUF+1Y5QZuK0Go8V8gaQyOwkFwjVguagyTedC2F7zLJBnCHxb24yWmzrN1uC9ztWn21fbhMZNZEC6Dbmxjn4Lifx3m1SGzTsiMjgZHPGk7z+nkk9Ptee2GD0TBKhZoXsVuI/f2zQOLza7HiM7+YadsDxqcctmKIeAOtS5He+F8V3vJeimAhy1AGIoWpBFGTIIcUmI69xNrEKjHj5ypyiFeu+nucfWVcGzl0uBLg3ElCb+CAwPE3Q/mDFTdHr182OlNwOdfJCXl9/uEGuxviYswu98YykTywuMtp3op6A/fUg2ARiZZE13AVnFLbmQKBtOyz/58T+bEay3ISKm144Mn4i/N+YXRuCwkvK730uxeTYb+ofCZaqyhrLU5JZlBdUug0B7ocNb1T73DEg6YPZw58ya2VW/J9rHpi/MJdZOJagvyUqDDo2JlIG2OUeGzC9+xSRmBY2VncJDeGjhRMPS,iv:AnoxDwzEEp9xOImFLcp+WqE69Ecd5fiWWtQiIeyK4+U=,tag:W1TvD9DKg7q/KoZ7A2IjJA==,type:str]
    #ENC[AES256_GCM,data:yDe6Qvt0ixk=,iv:6k4nHb2Kpgi6PJ1rrhrVWyL2kjPAuq0qGDb0Flco+EU=,tag:m/x4uDPqU7QPDRjShcpVTQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:86SR0l86,iv:smr2/I+dmTt/h1PJmyqSzU1Om04XoT14WfTZA5RSHzI=,tag:13leESDMVPaFKJD6SKkdxw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:g0GKvNgLUsfxNEQ8,iv:2yCgZWGYeAX1pQOEqVTX5FnkOZdv5pTizkOohRpFR2s=,tag:08sXlBlCurtnvxA5afxlWQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1aA0w0Vg3ghg6sF7Fz4wAl9ftJq8iw==,iv:rM6v8tJPAPzwKRjSoX6zTwlavZmMc1JDTePFG6PXeE0=,tag:VJgtuojbtCk1Y1aHTmb/uQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:uUxnaUbOXLckWFJdloYW/KMl0iNuBQ==,iv:xA/KZEjt3ljvdRnCIjFGPfl2ClA4dXltGn3aZEowgKs=,tag:THq/3TVI9rmZ3DuIUsTHmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2pWQW5XVHJlMkRvUm1K
            ZzRVNFJFeTg4VE5WaVpHKzB4ZnpyVmhOL2tjClBFRDBJeGVwd1VXejFHTDhTbkVT
            WmRDdldsbm9FY1RpRytFWDFPZkVUU1UKLS0tIERyMkNRUEtxN0JSS1Y0T3grTHpx
            R21kcElkdXFZNDFZbEZCVHJ0eWdxd1UKdmgn0EDysEgl0Dn35JC9d6133R9ByzCm
            oMBqLV2pINDQ9xixqTRBjqxxPYDTdwxfFsWEvow63kZAQ4Tm+e3wGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T03:35:30Z"
    mac: ENC[AES256_GCM,data:qv4bkpy7H/kZ8w9FrZAjeDo6TU101AEYDmsXbop+snan/fBTHpfZHUoxH05Jw2cZtw7XTsngKgZZqWOXbybemdG6LXB+Y8Xy2xCJk95LLphWxfVxMOTAI4PLn1xQNguWiQ/7UmLDYN4V4z+9D9IWzMK94eHZfVRSe6HK+k6Am8M=,iv:oqBv6RkW+2D5/l5JCEqfUnbReyUL3qu7IoNU80OcGIs=,tag:Gtax34/rhg2TLptGF+Qxlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
