apiVersion: v1
kind: Secret
metadata:
    name: kestra-secrets
    namespace: data-platform
stringData:
    KESTRA_CONFIGURATION: ENC[AES256_GCM,data:6TRom9+kQKzBZYNxzelVVSbbmO+rp0dcIvxyuGW+tNaSdVkqcm6xId6RzJ6kFAtVX6qKgSLodD8AMOqlpSpTE//gD/6I6NCCPv3CB55iSGGgGOecxqGM01Rf4YU7LZXrU/wFXWAQhtdUcUjoAUud+EQzlsxHb9nEJT6ADr1OTmk3JxZ8/ubQ+3yD//KeTMGCNtsGCB//O1TPdVOKWW47HWEoHExxn5fD22tC85G1GrbvenzxG+9/bcl9n8ds5tA2beVuPikRDF8yzNIxaGz6jwdptq7sRlVpZl5nUxqExADsFvysZPe3V5KOqJIQldpdOrjYfr2h6SF0lUrviGYIJ3sAqUeuJMzne2mhWI78E8DOP3JjfoJiVl+QmrRtNqBDFfyWxY0KgOWR6a3PJtZtSay5isyodAyc7DcV345vYs+6z9Am+NGXqbsvznBKm37DYn+V0Pz7XGE8eYEZwdLpI3vG3WIqh0jc2yM7kvzRcOCWKvivPCX0s0SbcFBzwDzZpGPIZ9QdY36WzzNhr80fCORzR0nqRp4zDclYfxEikV3HVB1/yIxxbCLv4FzLD6CqHBO0Hy2cTkoJBSldsRm9v4K9vZA78EtibGjGObGmHfnt29uZ4nUZEA6sUvHsi7aG+OMD55r23DQ5wGYC3nfxrEochS+iMdtjfEkI1sSe8RHHQ7qAlHRYbhVpwcfnJ9/YBI04TJ4p7x+DsHbfLwM=,iv:xY2J+Q6oweAiJBF+E0O9NOP08iEFrdOw5/GdzggRBTs=,tag:XPlsxaPkJ4jPecsIE2Z7tg==,type:str]
    #ENC[AES256_GCM,data:yDe6Qvt0ixk=,iv:6k4nHb2Kpgi6PJ1rrhrVWyL2kjPAuq0qGDb0Flco+EU=,tag:m/x4uDPqU7QPDRjShcpVTQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:86SR0l86,iv:smr2/I+dmTt/h1PJmyqSzU1Om04XoT14WfTZA5RSHzI=,tag:13leESDMVPaFKJD6SKkdxw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:g0GKvNgLUsfxNEQ8,iv:2yCgZWGYeAX1pQOEqVTX5FnkOZdv5pTizkOohRpFR2s=,tag:08sXlBlCurtnvxA5afxlWQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1aA0w0Vg3ghg6sF7Fz4wAl9ftJq8iw==,iv:rM6v8tJPAPzwKRjSoX6zTwlavZmMc1JDTePFG6PXeE0=,tag:VJgtuojbtCk1Y1aHTmb/uQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:uUxnaUbOXLckWFJdloYW/KMl0iNuBQ==,iv:xA/KZEjt3ljvdRnCIjFGPfl2ClA4dXltGn3aZEowgKs=,tag:THq/3TVI9rmZ3DuIUsTHmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2pWQW5XVHJlMkRvUm1K
            ZzRVNFJFeTg4VE5WaVpHKzB4ZnpyVmhOL2tjClBFRDBJeGVwd1VXejFHTDhTbkVT
            WmRDdldsbm9FY1RpRytFWDFPZkVUU1UKLS0tIERyMkNRUEtxN0JSS1Y0T3grTHpx
            R21kcElkdXFZNDFZbEZCVHJ0eWdxd1UKdmgn0EDysEgl0Dn35JC9d6133R9ByzCm
            oMBqLV2pINDQ9xixqTRBjqxxPYDTdwxfFsWEvow63kZAQ4Tm+e3wGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T23:23:20Z"
    mac: ENC[AES256_GCM,data:XKAHsFV71gzixJCT9q/DSA1eQBXODcds3JogJAAYN9Wijbcp8pPOSGsjS6WixzxUzoNNdmbCIc4w2jIkDC6mUWb9sCuggfgJ02FzB3BLaxqp6hAC7jydYO+Oh9BoX7FKPSy7MRRXTwYR9yGgSi2I+wq/z1/zxHiScDDUorw7gk4=,iv:tod9cb0yPMfJKuYWt0eLWrAzUIONWIGOQ/LN3zTt3mQ=,tag:QTD4jGCshzx+3iCSwndGHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
