---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 1
  imageName: ghcr.io/bo0tzz/cnpgvecto.rs:16.1-v0.1.11

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: local-storage

  superuserSecret:
    name: cloudnative-secrets

  enableSuperuserAccess: true

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
