---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cloudnative-secrets.sops.yaml
  - ./helmrelease.yaml
  - ./primary/cluster.yaml
  - ./primary/service.yaml
  # - ./pgvector/cluster-vector.yaml
  # - ./pgvector/service-vector.yaml
  # - ./lake/cluster.yaml
  # - ./lake/service.yaml
  # - ./datawarehouse/cluster.yaml
  # - ./datawarehouse/service.yaml
  # - ./fourteen/cluster.yaml
  # - ./fourteen/service.yaml
