---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./cloudnative-secrets.sops.yaml
  - ./helmrelease.yaml
  - ./primary/cluster.yaml
  - ./primary/service.yaml
  - ./pgvector/cluster-vector.yaml
  - ./pgvector/service-vector.yaml
