---
apiVersion: v1
kind: Service
metadata:
  name: cloudnative-pg-vector
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocal: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-vector
    role: primary
  loadBalancerIP: 10.172.90.56
