---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-fluentd
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-eck-app
  path: ./kubernetes/apps/monitoring/fluentd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 5m
