---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: &ns data-platform
spec:
  interval: 15m
  chart:
    spec:
      chart: jupyterhub
      version: 3.3.7
      sourceRef:
        kind: HelmRepository
        name: jupyter
        namespace: flux-system

  values:
    hub:
      # initContainers:
      #   - name: 01-init-db
      #     image: ghcr.io/onedr0p/postgres-init:16
      #     envFrom:
      #       - secretRef:
      #           name: &secrets jupyter-secrets
      existingSecret: jupyter-secrets
      db:
        type: postgres

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Dev Notebooks
        gethomepage.dev/group: *ns
        gethomepage.dev/icon: jupyter.png
        gethomepage.dev/name: Jupyter
      hosts:
        - &host "jupyterhub.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
