apiVersion: v1
kind: Secret
metadata:
    name: jupyter-secrets
    namespace: data-platform
stringData:
    hub.db.password: ENC[AES256_GCM,data:yvMNM4ceMODt/siw8CCnVykDL3kTjRyQFg==,iv:YBYblXyWjnSdID1b2PK4a+06iFrFgQ2es3RPYxrnl58=,tag:UsqmULSGWUGYyANPHesK9Q==,type:str]
    hub.db.url: ENC[AES256_GCM,data:FCDycYxzvI0j+26xtoFODjX1yEL6F2T9s2luFhIVWmAxm+ojqB7IdN743Mx5AymFUeqZLUVEVRnmeEqK3yoQEOeXvFhCAcrHkJSboz3vdeqzTRtGGsFpSaN75uc=,iv:qL9XXXjTH/aMcs+D4HyUI76b6OV/gXfMkP/3G1nEhiE=,tag:cnDA639YZNqbABvln+LuSA==,type:str]
    #ENC[AES256_GCM,data:OUcEKqVz0fk=,iv:hawKl4bs1XpiQ7VTHFkLEZgE7XGdatwm2INQ3RG2fZQ=,tag:hDNbK6WZuvcSVcR9S+UYWQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:7Z3//KQAVg==,iv:SH1+cdpLmBUCinLEJTyq4RL0nukYnY3Tid9+kyrfYIM=,tag:x96qbYWPdBxoFiZT6LteZQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:AYwHgC9ETwlozNFq6w==,iv:1pJKATIVGOpArW+bslToT6hFyDWVZrKJhDVb6+Eq0S8=,tag:6m9+Q7X7OjjDXBpi09XNzQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:uiWoL+RK3px3jCu6omYBFPyTguZbDyNkAA==,iv:iubcBEjK+0UdR/tw5QCPpD4l8/3yTWvpCgpdLnAY5fQ=,tag:wVofHViqt/EfpGrLQiABmw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ECe6eAnEq3nZU5+cM+Q9xmxMTk/i3Q==,iv:jSm0CUW/tguSijZZ8ZMt3WwRw+yb34Rp6gTA7g1BvGo=,tag:Z7Vk4yP9L6o0HZvzfr/ByQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GfJS3I4RRlV8a3bjhTa0l5L4M8kt4Q==,iv:ECwlZD8S/QQZVuw1HG2NGGgJM2odRzs2SzF0t+VfYik=,tag:qz+83W0UiJ/rzYdS1OOEBA==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Q7qZzPVZjVrAqyRZaahf0dQ7,iv:iQFCkwiguNIIlRpdlbZlr+TOq8vGWuEzD2MTmPleA5Q=,tag:eXy4eMQbt7hAq/6hiHQNLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bGh3bGZQQThxSHVtRjNH
            OVlsZDhsblVBRHZaOGpnaXZlRzZScUNaNmtnCnFtbStrTW5oek9nUFBoUTNEYmlx
            dU1rb3NLWjU2OE9oSFJ0T05NU0ZaQVEKLS0tIG12K05UakFuVE5hdlQ0V2UrVlkx
            SUpEbWg2OW1ZZU9jMkEyWG5qUXVwTXMKH5a1FDQ75sRu1wC6DWZCKBo1fnRY0YGy
            RL55yPCbts0UnG/2HcsgFIHrXyVao9YlGZ0utCcOlibofFZqCFVU/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T20:23:40Z"
    mac: ENC[AES256_GCM,data:BRDl77P0GsEGqZuh4F2A2rTFVVdUz7vgjbbWnQH5TFKPwlKdhoEaafE+SUt0BN/B/+uhgV2pElKf5nLi0XK//YBtVM8XMOwGsWr1TRg9G8agk0RtRlwkzKgo5qlrf9jOTgTR1ikMeUiI2DX7NKgDZbJy+9ItwmeXPz6v9Fsxpo8=,iv:ABDbn1pzmalUlXrz1dm/1SYYsqRCuULmm084LltF36Y=,tag:nM9AOxoIi4r5HJN8BTj30A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
