---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app eck
  namespace: &ns monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: eck-operator
      version: 2.12.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system

  values:
    replicaCount: 1

    image:
      repository: docker.elastic.co/eck/eck-operator
      tag: 2.12.1
      pullPolicy: IfNotPresent
