---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
  - ./elastic.yaml
  # - ./kibana.yaml
  # - ./fluentd.yaml
  # - ./ingress.yaml
