---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system

  values:
    image:
      repository: influxdb
      tag: 1.8.10-alpine

    pdb:
      create: false

    adminUser:
      organization: "homesys"
      user: "admin"
      bucket: "default"
      existingSecret: "influxdb-secrets"

    persistence:
      enabled: true
      existingClaim: local-volume-database
      subPath: *app

    ingress:
      enabled: true
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Time Series DB
        gethomepage.dev/group: data-platform
        gethomepage.dev/icon: influxdb.png
        gethomepage.dev/name: InfluxDB
      hostname: "influxdb.${SECRET_DOMAIN}"
      tls: true
