apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secrets
    namespace: database
stringData:
    admin-password: ENC[AES256_GCM,data:EGSr+8fV5q1Kyoj0YL3HlkHjhC4=,iv:fJhaeX1PzC9qJ9PKXN3nPAnARUbG/P2C1ztJUCf1O00=,tag:iaRawO92r54T4Zddy4knpA==,type:str]
    admin-token: ENC[AES256_GCM,data:mB7vCPamYtnUidBvD8qnEAdYJ9GZ0A==,iv:X2x5Shtg1Hxj70mTt/ZjwW+4BNapJzvwrrrjGGrUix0=,tag:tDqN+VKRkNu1qptOg78oGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g9s64k2xkul5pekjhv9hgrz9csze3utwruyegkypyfxwd6hjqugq5wyxfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQck1tTXl3TGJJdDdJbjRk
            RDBqaGJ4cytNWmFiYzF2K3FvOGZoMjl2VjJ3Ckx3eXV0eTY0TmtUUGs1WGtVV1Bm
            eGxzY3kvUHlDamo0ZDVRakhGdVNRUXcKLS0tIE9JOG40ZXpacUNzWE9RYTdObXhx
            MVpEZFg3emQrY1dQWjVBNXFXMFlZVlEKh3aybmEl7Zq7k1vU8MXg2RO5bX/6XjuV
            vWSBTWF8xMjgKYvLmcN5NRS8VLBqoWysd0fF2TQz4Rp/5lqgT7V4dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T01:29:23Z"
    mac: ENC[AES256_GCM,data:0jirzRP+dahSX+/H7bSKk/wuuod89HmR4nKcSLMeLO8hhPXIxvFUAMZrfVMDNa0pfDYnZ4wVxhOs9V6Xh3noXr6Z/JaKQcBtqhUXfgQfp5Bgg0wVJhfjWWOBWQCgS5LmephuKzfOpagg3v95w6VZ0SZx9zVdXnfdrpCigpOCgx4=,iv:ZFAt34AHogJKW6eGj4w956tngF/0QKZlgYCsCLgoBjA=,tag:h7zTIQGjQHmF6PcC8CGsIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
