apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: &ns monitoring
spec:
  version: 8.13.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true

  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4505M
                limits:
                  memory: 5446M
          volumes:
          - name: elasticsearch-data
            emptyDir: {}
