---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app pgloader
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          schedule: "00 00 1 1 *"
        containers:
          main:
            image:
              repository: ghcr.io/dimitri/pgloader
              tag: 3.6.9
            envFrom:
              - configMapRef:
                  name: pgloader-config
            command:
              - pgloader
              - "sqlite:///nfs/$(SQLITE_DB)"
              - "pgsql://$(PG_USER)@$(PG_HOST)/$(PG_DB)"

    service:
      main:
        ports:
          http:
            port: 8000

    persistence:
      nfs:
        existingClaim: nfs-volume-database
