---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-volume
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-claims
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/claims
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-claims
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-claims
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-volume
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/nas/backups
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-volume
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: nas-volume
  storageClassName: local-storage

