---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-files
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-files
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-volume-files
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-pgadmin
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-pgadmin
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-volume-pgadmin
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-nobody
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tera/vols
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-nobody
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: local-volume-nobody
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/fileserver/backups/current
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homesys
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-volume
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi
  volumeName: nfs-volume
  storageClassName: local-storage
